### ISSUE TITLE
is it possible to use asp.net core default di with Castle DynamicProxy?

### ISSUE THREAD

**Issue by wswind** [khellang/Scrutor#103]
I use autofac to replace the default di now . And I'm trying  to use the default di for simplicity.
But the only problem left for me is that:
I used DynamicProxy from castle.core for aop logic.
Is it possible to use the default di with castle.core dynamic proxy like autofac does ?

http://www.castleproject.org/projects/dynamicproxy/
https://autofac.readthedocs.io/en/latest/advanced/interceptors.html

**Comment by khellang** [comment]
Hi @wswind! 👋

I'm not really sure as I've never used dynamic proxies with DI. You might want to ask the ASP.NET team in aspnet/Extensions. They can probably point you to something.

**Comment by wswind** [comment]
Thanks for your reply. Your project is awesome.
I'll close the issue since it's out of the scope.
