### ISSUE TITLE
Using DependencyModel

### ISSUE THREAD

**Issue by adamhathcock** [khellang/Scrutor#11]
Have you thought about having Scrutor dependent on DependencyModel so that you don't have to specify assemblies at all?
https://github.com/dotnet/cli/tree/rel/1.0.0/src/Microsoft.Extensions.DependencyModel

**Comment by khellang** [comment]
Not really, you still need an assembly reference to load the `DependencyContext`.

How do you envision the API? You just pass a `DependencyContext` and scan all of its runtime libraries? Sounds like a quick extension method to write :smile:

```csharp
public static AssemblySelectorExtensions
{
    public static IImplementationTypeSelector FromDependencyContext(this IAssemblySelector selector, DependencyContext context)
    {
        return selector.FromAssemblies(context.RuntimeLibraries.SelectMany(lib => lib.Assemblies));
    }
}
```

```csharp
var collection = new ServiceCollection();

collection.Scan(scan => scan
    .FromDependencyContext(DependencyContext.Default)
        .AddClasses()
        .AsImplementedInterfaces()
        .WithTransientLifetime());
```

**Comment by adamhathcock** [comment]
Fair enough.  Just wanted to ask.  I only discovered the package yesterday.
