### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'Scan'

### ISSUE THREAD

**Issue by VibinKesavan** [khellang/Scrutor#114]
```
    services.Scan(s => s
                .FromAssembliesOf(typeList)
                .AddClasses()
                .AsImplementedInterfaces());
```
I am getting compile error, but I have the Microsoft.Extensions.DependencyInjection 3.1.1 package installed and refereneced. I am not sure why that extension is not picking it up. 

Compile Error : ServiceCollectionExtensions.cs(18,22): error CS1061: 'IServiceCollection' does not contain a definition for 'Scan' and no accessible extension method 'Scan' accepting a first argument of type IServiceCollection' could be found (are you missing a using directive or an assembly reference?) 

![image](https://user-images.githubusercontent.com/15130669/74087620-1533a280-4a86-11ea-9b51-9dd38091a302.png)

**Comment by khellang** [comment]
I don't see any reference to Scrutor? 🤔

**Comment by VibinKesavan** [comment]
Hi Khellang, 
thanks a mil, yes that was the problem, apologize i couldn't update the post. That looks so weird to me , the extension exists in the dependency namespace, why that need scrutor ?

**Comment by VibinKesavan** [comment]
That would be a stupid question being in the scrutor repo. I was modifying an existing app which was using scrutor.
