### ISSUE TITLE
Scrutor Asp.NET Core extensions project

### ISSUE THREAD

**Issue by sefacan** [khellang/Scrutor#115]
Hi @khellang,
I created a extension project for asp.net core app

You can see details https://github.com/sefacan/Scrutor.AspNetCore

**Comment by khellang** [comment]
Nice, looks like a useful piece of magic ✨😎 I'm closing this issue though, as I'm not sure there's anything actionable in here 😅

**Comment by sefacan** [comment]
Thank you. We don't need do anything. I just shared with you.
