### ISSUE TITLE
Encountering StackOverflowException/Crash with Decorate<T>

### ISSUE THREAD

**Issue by Mike-E-angelo** [khellang/Scrutor#117]
Greetings!

First off, really nice work with this library.  It has worked very well for my purposes without issue.

Until now. 😁  It could be due to user error, however, so I wanted to check in and verify.

The issue I encountered was with using the `Decorate` method on my EntityFrameworkCore configuration.  I have managed to reduce this to the following solution:

https://github.com/Mike-E-wins/Scrutor.EntityFramework

In particular, the code to reproduce is here:

https://github.com/Mike-E-wins/Scrutor.EntityFramework/blob/master/Scrutor.EntityFramework/UnitTest1.cs#L9-L17

Note that I was able to remove all EntityFramework code and use a simple singleton registration to reproduce this issue (the actual code where I encountered this is scoped).

When executed, the code either results in a never-ending loop, a `StackOverflowException`, or a crashed process.

For further context, I was attempting to create an initialized database [due this issue here](https://github.com/dotnet/efcore/issues/11666).  So, I was attempting to do something along the line of the following when I encountered this issue:

```
.Decorate<ApplicationStorage>(x => {
	x.Database.EnsureCreated();
	return x;
})
```

My current workaround is to do the above with [LightInject's Decorate method](https://www.lightinject.net/designpatterns/#decorator-pattern), but I would rather stick to `IServiceCollection` extension methods if possible, if that makes sense.

Thank you for any assistance/consideration towards this matter.

**Comment by khellang** [comment]
Hmm, I wonder if this could be because the service is registered as self?

**Comment by Mike-E-wins** [comment]
It could be, @khellang.  It's not returning a new instance of a different type/reference, so that might be confusing things here.

**Comment by khellang** [comment]
Close by https://github.com/khellang/Scrutor/pull/155

**Comment by Mike-E-angelo** [comment]
Woohoo!  Thank you so much for your efforts @khellang, @Mariachi1231, and team. 🙏
