### ISSUE TITLE
Unable to resolve service for type 'System.Collections.Generic.List`1[Microsoft.Extensions.Logging.ILoggerProvider]'

### ISSUE THREAD

**Issue by riscie** [khellang/Scrutor#118]
Hi there!

First of all, thank you for developing this library. I've used it in many projects and it's really convenient not having to register all services by hand.

In the current project, I am batteling a problem. I have a class which extends `List<T>`:

```
  public class PagedList<T> : List<T>
    {
        public int CurrentPage { get; }
        public int TotalPages { get; }
     // ...
```

Now whenever this class exists, I think what happens is, scrutor tries to register `List<T>` in the DI container. This is not my intention and it fails obviously. Here is the beginning of the (long) stacktrace:

```
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostApplicationLifetime Lifetime: Singleton ImplementationType: Microsoft.Extensions.Hosting.Internal.ApplicationLifetime': Unable to resolve service for type 'System.Collections.Generic.List`1[Microsoft.Extensions.Logging.ILoggerProvider]' while attempting to activate 'icpms.Shared.Pagination.PagedList`1[Microsoft.Extensions.Logging.ILoggerProvider]'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostLifetime Lifetime: Singleton ImplementationType: Microsoft.Extensions.Hosting.Internal.ConsoleLifetime': Unable to resolve service for type 'System.Collections.Generic.List`1[Microsoft.Extensions.Options.IConfigureOptions`1[Microsoft.Extensions.Hosting.ConsoleLifetimeOptions]]' while attempting to activate 'icpms.Shared.Pagination.PagedList`1[Microsoft.Extensions.Options.IConfigureOptions`1[Microsoft.Extensions.Hosting.ConsoleLifetimeOptions]]'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHost Lifetime: Singleton ImplementationType: Microsoft.Extensions.Hosting.Internal.Host': Unable to resolve service for type 'System.Collections.Generic.List`1[Microsoft.Extensions.Logging.ILoggerProvider]' while attempting to activate 'icpms.Shared.Pagination.PagedList`1[Microsoft.Extensions.Logging.ILoggerProvider]'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Logging.ILoggerFactory Lifetime: Singleton ImplementationType: Microsoft.Extensions.Logging.LoggerFactory': Unable to resolve service for type 'System.Collections.Generic.List`1[Microsoft.Extensions.Logging.ILoggerProvider]' while attempting to activate 'icpms.Shared.Pagination.PagedList`1[Microsoft.Extensions.Logging.ILoggerProvider]'.) 
...
```

I am probably missing something obvoious here. How can I tell Scrutor to ignore `PagedList<T>` within my project?

**Comment by khellang** [comment]
Hi @riscie!

I'm not sure what your setup looks like, but it looks like it's registering a bit too much, yes. We've talked about adding additional filters, like `IEnumerable<T>`, but because it's a breaking change, we haven't done it yet. See https://github.com/khellang/Scrutor/issues/65.

I suggest you supply a filter when calling `AddClasses` that will register only the types you're after for now.

**Comment by riscie** [comment]
Hey, thank you for the quick answer!

I can see in my servics list, I have the following registrations:
```
System.Collections.Generic.IList`1[T]
System.Collections.Generic.ICollection`1[T]
System.Collections.Generic.IEnumerable`1[T]
System.Collections.Generic.IReadOnlyList`1[T]
System.Collections.Generic.IReadOnlyCollection`1[T]
```

I assume, those are the culprit? I am registering with scrutor using `AsImplementedInterfaces`, like in #65:

```
   services.Scan(scan => scan
                .FromAssemblyOf<Startup>()
                .AddClasses(publicOnly: false)
                .AsImplementedInterfaces()
                .WithTransientLifetime());
```

Can you help with how to unregister these generic Types from the services collection?

```
services.RemoveAll<?>();
```

**Comment by khellang** [comment]
First, I wouldn't recommend using `AddClasses` without _any_ filter. It will definitely register way more than you need. Especially when using `publicOnly: false`.

I'm not at a computer right now, so it's a bit hard to write the code, but essentially you want to enumerate through the service collection and check if the `ServiceType` is assignable to `IEnumerable`.

**Comment by riscie** [comment]
Your answer just crossed my edit above. Thank you again. I will look more into how I can construct my AddClasses filter. Thank you again!

**Comment by khellang** [comment]
Awesome! Thanks 😘
