### ISSUE TITLE
FromDependencyContext fails on Assembly.Load exceptions

### ISSUE THREAD

**Issue by coxp** [khellang/Scrutor#119]
FromApplicationDependencies calls FromDependencyContext but falls back to FromAssemblyDependencies if that method throws an exception.

We're having an issue where FromDependencyContext throws an exception on Assembly.Load depending on what versions of third-party dependencies we have installed. The fallback to FromAssemblyDependencies then leads to different behaviour as not all services are found that need to be registered.

The exception we are getting is System.BadImageFormatException.

"Could not load file or assembly 'dotnet-aspnet-codegenerator-design' or one of its dependencies. An attempt was made to load a program with an incorrect format."

Is there a reason why FromDependencyContext doesn't swallow Assembly.Load exceptions like FromAssemblyDependencies does?

**Comment by khellang** [comment]
> Is there a reason why FromDependencyContext doesn't swallow Assembly.Load exceptions like FromAssemblyDependencies does?

Not really. I just didn't think about it 😅 A PR would be welcome 😄

**Comment by coxp** [comment]
Pull request #120. Nothing fancy :)

**Comment by khellang** [comment]
Closed with https://github.com/khellang/Scrutor/pull/120

**Comment by khellang** [comment]
Pushed v3.2.1 😄
