### ISSUE TITLE
Support to get registrations

### ISSUE THREAD

**Issue by SharpNoiZy** [khellang/Scrutor#122]
Hi,

Unfortunately there is no way to get just the registrations (without create instances) from the ServiceCollection, but I have this usecase.

I do things with Scrutor like this:
```
serviceCollection.Scan(scan => scan
                .FromAssemblies(assemblies)
                .AddClasses(classes => classes.AssignableTo(typeof(ISubscribeOn<>)))
                .AsImplementedInterfaces()
                .WithScopedLifetime());
```

At this point Scrutor have all the types that are assignable to IEvent and register them, I would love to have a method/ a point to hook on to get the types before they are registred, can you somehow provide that?

**Comment by khellang** [comment]
Can't you just enumerate the service collection?

> I would love to have a method/ a point to hook on to get the types before they are registred, can you somehow provide that?

What would that hook do? What would you use it for?

**Comment by SharpNoiZy** [comment]
> Can't you just enumerate the service collection?

I don't understand what you mean, is there a way to get just types from the ServiceCollection instead of instances of that type?

I have the following:
[FilterA]
Event1 : IEvent
[FilterB]
Event2 : IEvent
[FilterA]
Event3 : IEvent

Scrutor finds them correctly with the code above and now I want them back, just the types as IList<Type> to them somewhere.

Usecase:
We have huge enterprise application which handles millions of events per day.
We have FilterAttributes on that Events, but currentyl the events get all instanciated with all there dependencies, then we go through the attributes, and see, "Shit, just Event 2 needs to get executed", so instanciating the other two was totaly unneccessary.

We want just the types to get the attributes from them and instanciat just the needed one.

**Comment by SharpNoiZy** [comment]
Just mention that I was a bit to fast to write the comments, have edit my first and my last one

**Comment by SharpNoiZy** [comment]
LOL, I'm so stupid, there is no way to get the types from ServiceProvider.
But in the ServiceCollection after the Scan Call there are in the way I want them.

So sorry.

**Comment by khellang** [comment]
No worries, glad you figured it out 😄
