### ISSUE TITLE
Scan based on string with namespace

### ISSUE THREAD

**Issue by kamnyborg** [khellang/Scrutor#123]
Hi and thank you for creating a convenient extension for dependency injection.
I was wondering if it's possible to get a scanner that takes in a string for a namespace, so that it can scan that assembly/assembly containing that namespace? Ex. scan.FromAssembly("Assembly.Namespace")

**Comment by khellang** [comment]
Hi @kamnyborg!

Since you closed the issue, I'm assuming you found the method? 😅

**Comment by kamnyborg** [comment]
@khellang Is there such a method..? :) I figured I didn't want to bother you so I closed this as there are other options, but I was looking for a method taking a string in for the assembly name, f. ex. scan.FromAssembly("Assembly.Namespace") :)

**Comment by khellang** [comment]
If you're referring to an assembly name, it would simply be a matter of getting a reference to an `Assembly` based in its name and passing that instead.

If you're referring to a namespace, that would be a bit harder as a namespace can be spread out across an arbitrary amount of assemblies. You'd basically be forced to just scan the assemblies already loaded (`FromApplicationDependencies`). For that, there's already the `InNamespaces`, `InNamespaceOf<T>`, etc. methods 😊
