### ISSUE TITLE
Register/Decorate BaseController with scrutor in asp net core 3.1

### ISSUE THREAD

**Issue by TonyStarkGR** [khellang/Scrutor#124]
I have posted a question regarding scutor here

https://stackoverflow.com/questions/62745607/decorate-basecontroller-with-scrutor-in-netcore-3-1?noredirect=1#comment110959520_62745607

So far I'm not able to get it to work. Any thoughts ? What am I doing wrong here ?

**Comment by khellang** [comment]
Looks like you got an answer on StackOverflow 😅
