### ISSUE TITLE
Updating dependencies for .NET Core >= 3.1 projects

### ISSUE THREAD

**Issue by mbp** [khellang/Scrutor#127]
Today when you add `Scrutor` to a .NET Core 3.1 project, you get the following transitive dependencies:

![image](https://user-images.githubusercontent.com/77322/92363794-5b231880-f0f2-11ea-87cb-918032a6e38d.png)

Specifically, I would like if Scrutor did not pull in Newtonsoft.Json via `Microsoft.Extensions.DependencyModel`

If Scrutor instead used `Microsoft.Extensions.DependencyModel` >= 3.0.0, this is fixed, because it uses System.Text.Json instead of Newtonsoft.Json for the NET Standard 2.0 target.

I suppose the reasoning for current dependency is to support .NET Core 2.1.

Would a PR adding a new netcoreapp3.1 target framework where the dependency is conditionally upgraded, be accepted?

**Comment by khellang** [comment]
Hello @mbp! 👋

Indeed, the current target set is to keep supporting 2.1 apps (as long as Microsoft supports them). I wouldn't mind a PR adding an additional target for 3.1 though 😉

**Comment by mbp** [comment]
Thought it would be easy; but adding .netcoreapp3.1 target framework introduces all sorts of nullable errors, I suppose due to improved annotations in .NET Core. At the moment, I don't feel comfortable fixing those :(

**Comment by khellang** [comment]
I'll give it a shot when I can find some time and see how far I get 😅

**Comment by hey-red** [comment]
Possible fix is suppress NU1605 or add this package:

`<PackageReference Include="Microsoft.NETCore.Targets" Version="3.1.0" PrivateAssets="all" />`

**Comment by khellang** [comment]
https://www.nuget.org/packages/Scrutor/3.3.0

**Comment by azhe403** [comment]
what about .NET 5?

**Comment by khellang** [comment]
What about it?
