### ISSUE TITLE
Strange behavior in Azure Functions

### ISSUE THREAD

**Issue by kinetiq** [khellang/Scrutor#128]
Any chance this might eventually work 100% in Azure Functions? It would be extremely useful. Thanks for the great project!

**Comment by khellang** [comment]
Hello @kinetiq! 👋

I don't really use Azure Functions myself, so I would require a bit of help 😅

Anything in particular that doesn't work? Doe you have an error/stack trace, or some more details?

I'd love to make it work 100%, but I need a bit more to work with 😉

**Comment by kinetiq** [comment]
Well... First off, thanks for the reply.

I have a separate projects for my Azure Functions and MVC Core, which is required. The following code works fine in Core, but in Azure Functions, I get errors saying that System.IdentityModel.Tokens can't be opened. Here's the code:

```
...

            services.Scan(scan => scan
                .FromApplicationDependencies()   // TRANSIENT
                .AddClasses(classes => classes.AssignableTo<ITransientService>())
                .AsSelf()
                .WithTransientLifetime()
                .FromApplicationDependencies()  // SCOPED
                .AddClasses(classes => classes.AssignableTo<IScopedService>())
                .AsSelf()
                .WithScopedLifetime()
                .FromApplicationDependencies()  // SINGLETON
                .AddClasses(classes => classes.AssignableTo<ISingletonService>())
                .AsSelf()
                .WithSingletonLifetime());

...
```

I found this: https://stackoverflow.com/questions/58540037/c-sharp-azure-function-v3-dependency-injection-assembly-scanning-with-scrutor/58611617#comment112774619_58611617

...And I implemented it. However, it actually doesn't register any classes for me.

Apparently DI in Azure Functions is built on ASP.Net Core's DI, but in their own words:

_Dependency injection in Azure Functions is built on the .NET Core Dependency Injection features. Familiarity with .NET Core dependency injection is recommended. There are differences in how you override dependencies and how configuration values are read with Azure Functions on the Consumption plan._

(from https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services)

Worth noting: I am able to register classes by just using .FromCallingAssembly, oddly enough. 

Any ideas? :)

**Comment by khellang** [comment]
Yeah, the culprit is probably `FromApplicationDependencies`. I'm assuming Azure Functions has a somewhat different hosting model than a regular ASP.NET Core (console) application and `FromApplicationDependencies` is probably the method with the most "host magic" in it.

I'd have to do some debugging in an Azure Function to figure out what's going on. In the meantime, I suggest using one (or more) of the other methods, or specifying the assemblies you want to scan manually 😊

**Comment by kinetiq** [comment]
So I did a version using .FromAssemblies(assemblies), where I get the assemblies from this method:

```
        private static List<Assembly> GetAssemblies()
        {
            var path = Path.GetDirectoryName(Assembly.GetCallingAssembly().Location);
            var assemblies = new List<Assembly>();

            foreach (string dll in Directory.GetFiles(path, "Keystone*.dll"))
            {
                assemblies.Add(Assembly.LoadFrom(dll));
            }

            return assemblies;
        }

```

It does produce the assemblies, as expected. I can see that they are exporting various types, and of course they work fine in the MVC project. But nothing gets registered.

So that is where I decided to reach out. Currently I am wiring up dozens of services by hand. :)

**Comment by khellang** [comment]
> But in Azure Functions, with this approach, nothing gets registered.

I'd there anyway to debug this behavior? Log something? 🤔

It's kinda weird that it doesn't work, but I guess it could be restricting access to the file system or something. Or it places the assemblies somewhere else.

**Comment by kinetiq** [comment]
I really don't know how to proceed. It loads the assemblies, and in debug mode I can click on them and see that they seem to export classes.

Let me know if you can think of something I can do to help :)

**Comment by khellang** [comment]
> Let me know if you can think of something I can do to help :)

Surely there must be a way to log stuff from a function? 

Just insert a bunch of log statements for locations, paths, assemblies, types etc. Somewhere, something isn't right.

There seems to be a bunch of confusion around this in Azure Functions, i.e. https://stackoverflow.com/q/49597721/682105

**Comment by khellang** [comment]
I would probably use `Assembly.Load` instead of `LoadFrom` as the latter has a different load context than the former (default). Dunno if it makes a difference, but could be worth a shot 😅

**Comment by kinetiq** [comment]
That does work! So I've got:

```
        /// <summary>
        /// Contains a list of assemblies to scan for services. These are used to load actual
        /// assemblies, which Scrutor can then scan.
        /// </summary>
        private static List<Assembly> GetAssemblies()
        {
            var names = new List<string>()
            {
                "Keystone.AzureFunctions",
                "Keystone.Logic",
                "Keystone.Data",
                "Keystone.Core"
            };

            return names
                .Select(Assembly.Load)
                .ToList();
        }
```

And then this gets called from Startup.Confgure:

```
            var assemblies = GetAssemblies();

            services.Scan(scan => scan
                // TRANSIENT
                .FromAssemblies(assemblies) 
                //.FromAssemblies(assemblies)
                .AddClasses(classes => classes.AssignableTo<ITransientService>())
                .AsSelf()
                .WithTransientLifetime()
                // SCOPED
                .FromAssemblies(assemblies) 
                .AddClasses(classes => classes.AssignableTo<IScopedService>())
                .AsSelf()
                .WithScopedLifetime()
                // SINGLETON
                .FromAssemblies(assemblies) 
                .AddClasses(classes => classes.AssignableTo<ISingletonService>())
                .AsSelf()
                .WithSingletonLifetime());
        }

```

So far this seems fine in both MVC, Blazor, and the Azure Functions project. I like that it isn't relying on janky paths which seem more likely to vary by environment.

Interestingly, I ran into a problem in my web project today as well with Scrutor. It normally hums along fine, but I recently added Blazor Server to the project (which worked pretty easily BTW). After I installed the trial version of the Progress / Telerik's Blazor UI components, there was a Sctutor issue similar to what I came across in the Azure Functions project, but this fixed that issue as well by bypassing thousands of classes I don't care about. I did not capture the exception, sadly.

**Comment by khellang** [comment]
Nice. Does that mean this issue is solved, or do you think there's anything to do in the library? BTW, you can drop the subsequent calls to `FromAssemblies` (and just keep calling `AddClasses`, which will pull from the assemblies from the first call.

**Comment by kinetiq** [comment]
Oh, good to know. 

Well, it might be good to publish some guidance for Azure Functions based on this thread. Maybe a note that one of the more common ways of operating will simply not work in that environment. :)
