### ISSUE TITLE
Optional Decorators?

### ISSUE THREAD

**Issue by sander1095** [khellang/Scrutor#133]
Hello!

I have the following setup. This code is very similiar to my earlier question: https://github.com/khellang/Scrutor/issues/68

```
            services.Scan(s =>
            {
                s.FromAssembliesOf(typeof(ApplicationLayerServiceProviderExtensions))
                    .AddClasses(p => p.AssignableTo(typeof(ICommandHandler<>)).Where(x => !x.IsGenericType))
                    .AsClosedTypeOf(typeof(ICommandHandler<>))
                    .WithTransientLifetime();

                s.FromAssembliesOf(typeof(ApplicationLayerServiceProviderExtensions))
                    .AddClasses(p => p.AssignableTo(typeof(AbstractValidator<>)).Where(x => !x.IsGenericType))
                    .AsClosedTypeOf(typeof(IValidator<>))
                    .WithTransientLifetime();
            });

            services.Decorate(typeof(ICommandHandler<>), typeof(ValidationCommandHandlerDecorator<>));
            services.Decorate(typeof(ICommandHandler<>), typeof(LoggingCommandHandlerDecorator<>));
```

The `AsClosedTypeOf()` code is this:

```
        public static ILifetimeSelector AsClosedTypeOf(this IServiceTypeSelector selector, Type closedType)
        {
            return selector.As(t => t
                .GetInterfaces()
                .Where(p => p.IsGenericType && p.GetGenericTypeDefinition() == closedType)
            );
        }
```

my `ValidationCommandHandlerDecorator<>` looks like this:

``` 
    public class ValidationCommandHandlerDecorator<TCommand>
        : ICommandHandler<TCommand> where TCommand : ICommand
    {
        private readonly ICommandHandler<TCommand> _innerHandler;
        private readonly IValidator<TCommand> _validator;

        public ValidationCommandHandlerDecorator(
            ICommandHandler<TCommand> innerHandler,
            IValidator<TCommand> validator)
        {
            _innerHandler = innerHandler;
            _validator = validator;
        }

        public Task HandleAsync(TCommand command)
        {
            var validationResult = _validator.Validate(command);

            // Other code is omitted

            return _innerHandler.HandleAsync(command);
        }
    }
```

Right now, I need to create an implementation of `IValidator<>` for every command that gets executed. If it does not exist, an exception is thrown because the implementation can't be found.

I would like to support that `Ivalidator<>` is optional. Sometimes I have a command that I need no validator for. Right now I HAVE to create an implementation of `IValidator<>` that is just an empty class to satisfy this code. 

Could you help me out?

**Comment by sander1095** [comment]
Also, bonus question!

I have noticed there are some new features in Scrutor that my project does not benefit from. Are there any that you think I could use, based on my given code? For example, getting rid of that `AsClosedTypeOf` or something?

Thanks!

**Comment by khellang** [comment]
Hi @sander1095! 👋🏻 

I think you could get around it by either defining two constructors on `ValidationCommandHandlerDecorator<>`; one with `IValidator<>` and one without. The container will then pick the "best" one based on its available registrations. 

Otherwise you could try injecting `IEnumerable<IValidator<>>` and do a `FirstOrDefault`. If the result is `null`, you don't have an available validator and can safely just invoke the decorated handler.

> Are there any that you think I could use, based on my given code? For example, getting rid of that `AsClosedTypeOf` or something?

The code looks fine 🤩 I don't think there's anything built-in that does exactly the same as `AsClosedTypeOf`. There's `AsImplementedInterfaces`, but that would potentially register more stuff.

**Comment by khellang** [comment]
It could also be possible to keep a single constructor, but make the validator optional (`IValidator<TCommand> validator = null`). I think the container supports it :)

**Comment by sander1095** [comment]
Thank you very much, I will try this out!

**Comment by sander1095** [comment]
I am now using your last suggestion  (IValidator<TCommand> validator = null) and that works! thanks!
