### ISSUE TITLE
System.ArgumentException with constrained generics

### ISSUE THREAD

**Issue by lawrencek76** [khellang/Scrutor#138]
Calling Decorate with a decoratorType that is constrained may throw a System.ArgumentException trying to create the decorator with MakeGenericType.

Until [this](https://github.com/dotnet/runtime/issues/28033) api is added to the dotnet runtime it seems the only reasonable option is to try catch and eat the exception [ref](https://stackoverflow.com/questions/4864496/checking-if-an-object-meets-a-generic-parameter-constraint/4864565#4864565).

**Comment by khellang** [comment]
Closed with #139
