### ISSUE TITLE
Decorate generic types

### ISSUE THREAD

**Issue by rakhimzhanov** [khellang/Scrutor#141]
Hi team,

Is there any way to register below generic types?

```
services.AddTransient(typeof(IReadRepository<,>), typeof(ReadRepository<,>));
services.Decorate(typeof(IReadRepository<,>), typeof(CachedReadRepository<,>));
```

Currently I got the exception like this:
```
Scrutor.MissingTypeRegistrationException: Could not find any registered services for type 'WebApi.Infrastructure.Repositories.IReadRepository<TEntity, TResponse>'
```

**Comment by khellang** [comment]
Yeah, decorating open generic types isn't supported very well for the reasons [outlined here](https://github.com/khellang/Scrutor/issues/14#issuecomment-256874081).

It's partly supported by having fully closed registrations in the collection (i.e. by scanning using `IsAssignableTo` and `AsImplementedInterfaces`) before decorating. In that case it will use the type arguments of the closed services to "fill in" the arguments of the decorators services.

That's unfortunately as far as we'll get with the built-in container 😞

**Comment by rakhimzhanov** [comment]
Dear khellang,

Thanks for the answer and your wonderful library.
Hope we will have this feature in the future.
