### ISSUE TITLE
Difference between InNamespaceOf and InExactNamespaceOf

### ISSUE THREAD

**Issue by marcominerva** [khellang/Scrutor#145]
Among the others, the **IImplementationTypeFilter** interface defines the **InNamespaceOf** and **InExactNamespaceOf** methods. What is the difference between these?

**Comment by khellang** [comment]
Hello @marcominerva! 👋

AFAICR, `InNamespaceOf` will also include sub-namespaces, while `InExactNamespaceOf` will only match exactly the same namespace:

https://github.com/khellang/Scrutor/blob/a949cd24726cfb0bc081a95e1e33fb5b6ea05f94/src/Scrutor/ReflectionExtensions.cs#L60-L89
