### ISSUE TITLE
Is it possible to use scrutor with `Lazy`?

### ISSUE THREAD

**Issue by rafek1241** [khellang/Scrutor#146]
In microsoft DI I can do something like that:
```
 collection.TryAddScoped<Lazy<SomeClass>>(
                            provider => new Lazy<SomeClass>(
                                () => provider.GetService<SomeClass>()
                            )
                        );
```
Can I do the same in scrutor?

**Comment by khellang** [comment]
Hi @rafek1241! 👋

There's really no difference between Scrutor and MS.Ext.DI. Scrutor is just a couple of extension methods on `IServiceCollection`. The rest is Microsoft's DI container 😁

**Comment by martindybal** [comment]
I'm reopening this issue. Because from the answer I don't know how to use Scrutor to register Lazy<T>. Let's say I want to register all implementations of `ITransientService` as `Lazy<MyTransientService>`. How do I do that? Something like:
```cs
services.Scan(scan => scan
    .FromAssemblyOf<ITransientService>()
    .AddClasses(classes => classes.AssignableTo<ITransientService>())
    .AsSelfLazy());
```

**Comment by jpeckham** [comment]
does anyone know? I am interested in doing the same thing. Perhaps some sort of custom registration per concrete?
