### ISSUE TITLE
Decorating EF Core's DbContext

### ISSUE THREAD

**Issue by leoshusar** [khellang/Scrutor#148]
Hi!
I am currently trying this library for DB audit logging.
I currently have it working for MongoDB - I am using `IMongoRepository` here.
But is there any way to decorate EF Core's DbContext too?

I tried this decorator

```cs
class AuditLogDbContextDecorator : DbContext
{
    private readonly DbContext _decorated;

    public AuditLogDbContextDecorator(DbContext decorated)
    {
        _decorated = decorated;
    }

    public override int SaveChanges()
    {
        LogChanges();
        return _decorated.SaveChanges();
    }

    private void LogChanges()
    {
        ...
    }
}
```

and decorated it like this: `builder.Services.Decorate(typeof(DbContext), typeof(AuditLogDbContextDecorator));`
but this fails with
```
Scrutor.MissingTypeRegistrationException: 'Could not find any registered services for type 'Microsoft.EntityFrameworkCore.DbContext'.'
```

When I decorate my context implementation: `builder.Services.Decorate(typeof(MyContext), typeof(AuditLogDbContextDecorator));`
it works, but then it (probably) deadlocks when I want to retrieve my context either in constructor or by `GetService<MyContext>()`. No error, no exception, it just hangs. Even Ctrl + C won't stop the app, I have to close it using the stop button in VS.

Do you know what can be causing this? I was thinking about circular dependency, could it be? Is it even possible to decorate partial abstract class like DbContext?

**Comment by khellang** [comment]
Hmm, yeah, that's a tricky one. You're essentially decorating a concrete registration as opposed to an interface registration 🤔

I think what's causing the hang might be the injected `DbContext` in the decorator.

The rule of thumb should basically be that you should inject the exact same type as you decorate. That means you probably should inject `MyContext` instead.

I haven't really tried this scenario myself, but I can't see why it shouldn't work 😅

**Comment by leoshusar** [comment]
If you meant like this:

```cs
public class AuditLogDbContextDecorator<TContext> : DbContext where TContext : DbContext
{
    private readonly TContext_decorated;

    public AuditLogDbContextDecorator(TContext decorated)
    {
        _decorated = decorated;
    }
}
```

and register like this

```cs
builder.Services.Decorate(typeof(MyContext), typeof(AuditLogDbContextDecorator<MyContext>));
```

this doesn't work either :( still hangs

**Comment by khellang** [comment]
Hmm, yeah, that's exactly what I meant 😅 I'm not really sure what's going on. Need to take a look at this and do some debugging...

**Comment by khellang** [comment]
Closed by https://github.com/khellang/Scrutor/pull/155
