### ISSUE TITLE
Move the Scan extension under the Microsoft.Extensions.DependencyInjection namespace

### ISSUE THREAD

**Issue by micdenny** [khellang/Scrutor#15]
This will avoid include the `using Scrutor` and is the way Microsoft and third party components extends the framework.

some examples:

- [Microsoft.EntityFrameworkCore -> ServiceCollectionExtensions](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs)
- [Microsoft.EntityFrameworkCore -> DbContextOptionsExtensions](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerDbContextOptionsExtensions.cs)
- [EntityFramework.SqlServerCompact](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Extensions/SqlCeDbContextOptionsExtensions.cs)
- [serilog-extensions-logging-file](https://github.com/serilog/serilog-extensions-logging-file/blob/dev/src/Serilog.Extensions.Logging.File/Microsoft/Extensions/Logging/FileLoggerExtensions.cs)

**Comment by khellang** [comment]
Sure, I guess we could do that. This is a binary level breaking change, though, so I think we'll have to spare this for when we're going for a new major release :smile:

**Comment by micdenny** [comment]
If we don't want to bother developers with this breaking change, we could think to leave both versions and push a minor release flagging the old one as [Obsolete()], then wait some time before push the major without the obsolete one.

**Comment by khellang** [comment]
If someone's willing to PR the methods, then maybe.

**Comment by micdenny** [comment]
@khellang I can't restore packages for the `Scrutor.Tests` project:

![image](https://cloud.githubusercontent.com/assets/1633595/22327941/0d5fdf82-e3ba-11e6-8ad3-15ed54321d67.png)

![image](https://cloud.githubusercontent.com/assets/1633595/22327946/1139d61c-e3ba-11e6-9ef8-d685b4d605c6.png)

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "C:\Users\micde\Documents\Git\Scrutor\.vs\restore.dg"
log  : Restoring packages for C:\Users\micde\Documents\Git\Scrutor\test\Scrutor.Tests\project.json...
error: Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\micde\Documents\Git\Scrutor\test\Scrutor.Tests\project.lock.json
log  : C:\Users\micde\Documents\Git\Scrutor\test\Scrutor.Tests\Scrutor.Tests.xproj
log  : Restore failed in 619ms.
Errors in C:\Users\micde\Documents\Git\Scrutor\test\Scrutor.Tests\Scrutor.Tests.xproj
    Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
NuGet Config files used:
    C:\Users\micde\Documents\Git\Scrutor\NuGet.Config
    C:\Users\micde\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
Feeds used:
    https://api.nuget.org/v3/index.json
```

**Comment by khellang** [comment]
`netstandard1.6` is definitely compatible with `netcoreapp1.0`. Something's telling me you don't have the correct tooling?

**Comment by micdenny** [comment]
> netstandard1.6 is definitely compatible with netcoreapp1.0

it definitively should 😄 

> Something's telling me you don't have the correct tooling?

actually I had to install the old tooling `1.0.0-preview1-002702` because is specified in the [global.json](https://github.com/khellang/Scrutor/blob/master/global.json)

**Comment by micdenny** [comment]
If I update on `global.json` the tool version to at least `1.0.0-preview2-003121` it works.

@khellang can you fix the tool version to at least that version?

**Comment by khellang** [comment]
Wanna send a PR? :smile:

**Comment by micdenny** [comment]
> Wanna send a PR? 😄

done #18

**Comment by micdenny** [comment]
After some try, I think if we want to move under `Microsoft.Extensions.DependencyInjection` namespace, it is easier to give a small breaking change without trying giving backward compatibility.

I will PR soon, then you will decide, BTW I think is the good direction.
