### ISSUE TITLE
Cannot call .FromAssemblies() repeatedly

### ISSUE THREAD

**Issue by seangwright** [khellang/Scrutor#150]
The following does not do what I expected it to do:

```csharp
var assemblies = new[] { typeof(A).Assembly, typeof(B).Assembly };

services.Scan(s => s
    .FromAssemblies(assemblies)
    .FromAssemblyOf<C>()
    .AddClasses(c => true, true)
    .AsImplementedInterfaces()
    .WithScopedLifetime());
```

Assuming `A`, `B`, and `C` all come from differently assemblies, only types from `C`'s assembly will be registered.

Each use of the `.FromXX()` calls clear the previous calls' assemblies.

It would be great if these calls could be used to build up a union collection of types instead of 'last one wins'.

**Comment by khellang** [comment]
Hi @seangwright! 👋🏻 

Yeah, that's just the way it works. It's exactly the same every time you call `AddClasses` 😅 Changing this now would be a major breaking change and is unlikely to happen.

Fortunately, it should be easy enough to add some extension methods around it to make it work however you'd like, or just build up the list of assemblies up-front 😄

**Comment by seangwright** [comment]
Could we add an extension (or set of them) like `.AddAssemblies()`, `.AddAssemblyOf<T>()` and add comments to both sets to indicate the functionality they have?

**Comment by khellang** [comment]
@seangwright It's not something I can do without rewiring a lot of the internals. The way it works is that every time you call `From{Something}`, you reset the source.

**Comment by seangwright** [comment]
No problem! At least the behavior is documented here.
