### ISSUE TITLE
.Net 6 support

### ISSUE THREAD

**Issue by Gavamot** [khellang/Scrutor#158]
Plz Guys, I am really need it.

**Comment by khellang** [comment]
Hi @Gavamot! 👋🏻 

People are happily using Scrutor with .NET 6. What's the issue?

**Comment by krismale** [comment]
I just upgraded my application to .NET 6 and have been using the IServiceCollection.Scan function to scan for all classes that are of type IInjectable for a while in .NET 5 without any issues. After upgrading to .NET 6 the scan function attempts to add all classes in the namespace (Integration.Standard in the example code below), even those that do not implement IInjectable. `services.Scan(scan => scan.FromAssemblies(typeof(Integration.Standard.IInjectable).Assembly).AddClasses().AsImplementedInterfaces().WithTransientLifetime());`

An example is this class here, which is part of the Integration.Standard namespace, but should NOT be added to the container as it does NOT implement the IInjectable interface:

`public class MachineLearningProxyException : Exception
    {
        public MachineLearningProxyException(string message, Exception e) : base(message, e)
        {

        }
    }`

Has any other users detected a similar issue?

**Comment by khellang** [comment]
> After upgrading to .NET 6 the scan function attempts to add all classes in the namespace (Integration.Standard in the example code below), even those that do not implement IInjectable. `services.Scan(scan => scan.FromAssemblies(typeof(Integration.Standard.IInjectable).Assembly).AddClasses().AsImplementedInterfaces().WithTransientLifetime());`

There's no filter on that method call, so it should've always added all types in the specified assembly 😅

**Comment by khellang** [comment]
If you wanted to only register types assignable to `IInjectable`, you should've included an `AssignableTo<IInjectable>()` filter:

```csharp
collection.Scan(scan => scan
    .FromAssemblyOf<Integration.Standard.IInjectable>()
        .AddClasses(classes => classes.AssignableTo<Integration.Standard.IInjectable>())
            .AsImplementedInterfaces()
            .WithTransientLifetime());
```

**Comment by krismale** [comment]
wouldn't the `scan.FromAssemblies(typeof(Integration.Standard.IInjectable).Assembly` part filter out and look for classes that implement IInjectable? Or am I missunderstanding Scrutor very badly?

**Comment by khellang** [comment]
> Or am I missunderstanding Scrutor very badly?

I think you are, yes 😅 That's just telling Scrutor in which assemblies to look for types. You then filter those types inside `AddClasses` as shown above.

**Comment by khellang** [comment]
> Okay, so I can just remove IInjectable from the typeof section in FromAssemblies?

If you still want to scan the assembly of `IInjectable`, then you can keep it.

> Or is that class used to figure out which assembly it is defined in?

Yes, that's it. I think it's a bit more clear when using `.FromAssemblyOf<Integration.Standard.IInjectable>()` 😄

**Comment by krismale** [comment]
> I think it's a bit more clear when using `.FromAssemblyOf<Integration.Standard.IInjectable>()`

Yes, that function name was a bit easier to interpret. Thanks for the quick response! 😄
