### ISSUE TITLE
Decorating multiple different implementations of the same service.

### ISSUE THREAD

**Issue by ericvruder** [khellang/Scrutor#160]
Let's say I have a interface called IRepository, where I have 2 different implementations: SqlServerRepo and PostGresRepo.

I register these two as such :
```csharp
collection.AddScoped<IRepository, SqlServerRepo>();
collection.AddScoped<IRepository, PostGresRepo>();
```

My usage pattern would to inject all of the repositories and then iterate over them, or maybe follow a strategy pattern on some exposable property. So something like this: 

```csharp
class Service
{
    private readonly IEnumerable<IRepository> repos;
    public Service(IEnumerable<IRepository> repos)
    {
        this.repos = repos;
    }

    public void ResetAllRepos()
    {
        foreach(var repo in repos)
        {
            repo.Reset();
        }
    }
}
```
I now want to implement a logger called RepositoryLogger that implements the IRepository interface, that logs all calls made to each implementation. I would then like to decorate each implementation with the RepositoryLogger. That would mean I would have an object graph that looked kinda like this:

Service -> RepositoryLogger -> SqlServerRepo
Service -> RepositoryLogger -> PostGresRepo

I used to be able to do this with ninject and named registrations. I'm pretty sure I can find some code that achieved that, if you are still uncertain of what I mean. But I can't for the life of me wrap my head around how I would be doing this in Structor. Is this a supported scenario? How would I achieve this?

**Comment by khellang** [comment]
Hmm. You want to decorate all registrations of `IRepository` with `RepositoryLogger`? What happens if you call `Decorate<IRepository, RepositoryLogger>()`?

**Comment by ericvruder** [comment]
That just works 🤦‍♂️ I just remember having such a hard time getting it to work on ninject, I wasn't expecting it to just work out of the box.  Sorry for wasting your time :(

**Comment by khellang** [comment]
No worries, glad you got it working! 😅👍
