### ISSUE TITLE
Update Microsoft.Extensions.DependencyModel dependency on .NET standard 2.0

### ISSUE THREAD

**Issue by KuraiAndras** [khellang/Scrutor#162]
We are using this project in unity, but right now the only way to consume it, is to put the DLL under version control inside the Assets folder. We would like to consume this project as a NuGet package utilizing [xoofx's UnityNuGet project](https://github.com/xoofx/UnityNuGet). Right now I can't add Scrutor to the nuget registry because the .NET standard 2.0 version has a dependency on Microsoft.Extensions.DependencyModel Version 2.1.0, but for Unity only versions 3.0.0 and higher are supported.

**Comment by KuraiAndras** [comment]
I have created a PR for this #163

**Comment by khellang** [comment]
Closed by #163
