### ISSUE TITLE
Generics scanning/registration doesn`t work well?

### ISSUE THREAD

**Issue by alexey-velichko** [khellang/Scrutor#168]
Hi! 
I use a MediatR package to orchestrate commands in my app. I need to implement some "per-request" validation logic, so I defined an interface:

	public interface IValidator<in TRequest, TResponse> where TRequest : IRequest<TResponse>
	{
		Task Validate(TRequest request, CancellationToken cancellationToken);
	}
	
then implemented a request and it`s validator:

	public class SayHelloRequest : IRequest<string>
	{
		public string Name { get; }
		public SayHelloRequest(string name)
		{
			Name = name;
		}
	}

	public class SayHelloValidator : IValidator<SayHelloRequest, string>
	{
		public async Task Validate(SayHelloRequest request, CancellationToken cancellationToken)
		{
		}
	}
Manual validator registration produces too much boilerplate code, so I`ve used Scrutor:

	new ServiceCollection()
	.Scan(
		c => c.FromExecutingAssembly()
		      .AddClasses(classes => classes.AssignableTo(typeof(IValidator<,>)))
		      .AsImplementedInterfaces()
		      .WithSingletonLifetime()
	)

But when I try to resolve a particular validator I always get null from container. Here is a simple repro: https://github.com/alexey-velichko/ScrutorScanningProblemRepro. I seem to have missed something when configuring Scrutor scanning. Would appreciate any hint on how to make this work.

**Comment by dmdnkv** [comment]
Hi.

I did debug your sample, and it looks like "FromExecutingAssembly" determined the assembly as Scrutor.dll. Therefore, there is none of your defined classes there. 

It works If you change it to "FromEntryAssembly".

```
ScrutorScanningProblemRepro.exe
Validator1 is null: False
Validator2 is null: False`

**Comment by khellang** [comment]
Yeah, there's an unfortunate misconception in those APIs; see #92

**Comment by alexey-velichko** [comment]
@dmdnkv @khellang Thank you so much! :)
