### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by jvmlet** [khellang/Scrutor#187]
Would you please expose  `ReflectionExtensions` class as public ?

**Comment by khellang** [comment]
Hi @jvmlet! 👋🏻 

I'd like to avoid littering `Type` with all kinds of extension methods for all consumers of the library.

Any particular method you're interested in? Feel free to just copy the code if there's anything you need 😊

**Comment by jvmlet** [comment]
I understand the issue with exposing extension methods as public....
Then maybe an interface with default implementations that gets `Type` and internally uses extension methods? 
Or may be even replaces them? 
The extensions you have for `Type` are very rich and expressive, I haven't found the library that provides similar query API for `Type`. 
I'm using `Scrutor` discovery and filtering features, and will be great to have the same library to query the  `Type` without duplicating it.

**Comment by khellang** [comment]
I don't think it's right for this library to expose `Type` extension methods like that, but you're free to take the code and do whatever you like 😊
