### ISSUE TITLE
The latest Scrutor NuGet package is not compatible with net7.0

### ISSUE THREAD

**Issue by Arash-Sabet** [khellang/Scrutor#190]
Compiling a .NET 7.0 project referencing Scrutor causes the following compile error:

> error NU1202: Package Scrutor 1.0.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0)

**Comment by Arash-Sabet** [comment]
@khellang I associated a PR with this issue. Would you please review and merge it as this issue is a roadblock? Thanks.

**Comment by khellang** [comment]
Hello @Arash-Sabet! 👋

Why are you trying to install Scrutor 1.0.0 in a .NET 7 project? The latest version 4.2.0 targets .NET 6.0, which should be compatible with .NET 7. There should be no need to add a separate target for this.

**Comment by Arash-Sabet** [comment]
@khellang
The compile error message showed "Scrutor 1.0.0" but I'm sure it was the latest version of 4.2.0. 
Correction: I meant the latest version of 4.2.0 that we used causes our project not to compile and hence I modified the title of this issue. I think it's worth review the PR.

**Comment by khellang** [comment]
I've installed and used Scrutor in several .NET 7 projects without issues. I have a feeling the error message is correct and that this is a PEBKAC 😅

**Comment by khellang** [comment]
In fact, the test project is already targeting `net7.0`:

https://github.com/khellang/Scrutor/blob/9150e5e95ba4613d9906b66ea6005f4fd36b59ee/test/Scrutor.Tests/Scrutor.Tests.csproj#L3

https://github.com/khellang/Scrutor/blob/9150e5e95ba4613d9906b66ea6005f4fd36b59ee/test/Scrutor.Tests/Scrutor.Tests.csproj#L22-L24

And the CI build is happily using the .NET 7 SDK:

https://github.com/khellang/Scrutor/blob/9150e5e95ba4613d9906b66ea6005f4fd36b59ee/.github/workflows/build.yml#L24-L27

**Comment by Arash-Sabet** [comment]
@khellang 
Our .net 7.0 project has a similar configuration like Scrutor's test project. I produced a dll out of Scurtor's forked code and it addressed the issue. I think you should not have closed the PR without merging it. Did you review the Scrutor library's .csproj's slight augmentation in the PR? The error message I reported was produced during compilation in our VS 2022, CI/CD and Docker.

Unfortunately, we have to remove Scrutor from our project completely to be able to proceed.

**Comment by khellang** [comment]
> Our .net 7.0 project has a similar configuration like Scrutor's test project.

Can you post some (runnable) code instead? If you can produce a project targeting .NET 7 that won't work with Scrutor 4.2.0, I'll happily accept a PR, or even fix it myself, but as I said, everything works perfectly fine using Scrutor 4.2.0 with .NET 7. I just created a new project, installed Scrutor, built and ran it without any issues.

> I think you should not have closed the PR without merging it. Did you review the Scrutor library's .csproj's slight augmentation in the PR?

I did, and the PR was incomplete as it didn't even add a .NET 7 target framework. You can't possible have tested that code, as it did nothing 😅

> The error message I reported was produced during compilation not only in VS 2022, but also the CI pipeline and Docker.

But why is it complaining about Scrutor 1.0.0? You're definitely not telling the whole truth. I've already wasted way too much time on this, so unless you can produce a repro for this issue, things will stay as they are 😞

**Comment by khellang** [comment]
If I switch to Scrutor 1.0.0, as you've used, I get the exact same error, only with some extra details that you left out:

> error NU1202: Package Scrutor 1.0.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Scrutor 1.0.0 supports:
> error NU1202:   - dnx451 (DNX,Version=v4.5.1)
> error NU1202:   - dnxcore50 (DNXCore,Version=v5.0)

**Comment by Arash-Sabet** [comment]
@khellang 
Apparently somewhere the version 1.0.0 was cached despite the latest nuget package was referenced in the project! Thanks.
