### ISSUE TITLE
Conditional decoration and Strategy extension

### ISSUE THREAD

**Issue by waynebrantley** [khellang/Scrutor#192]
When decorating with your library and open generics, it looks like this (and works)
```
            services.Decorate(typeof(IQueryHandler<,>), typeof(QueryHandlerCacheDecorator<,>));
```
What I would like to do is decide on each Type (at registration time) if it should be decorated or not.
I might look for a ``[QueryCache]`` attribute or something to make that decision.

Given your latest release this should be very doable with the DecorationStrategy - I just overried the CanDecorate method.

This led me to several issues.
- OpenGenericDecorationStrategy is not public (I just want to inherit and override the CanDecorate)
- ReflectionExtensions public (Given OpenGenericDecorationStrategy not public - I tried to just make my own and not inherit - for now  to continue I just copied and pasted into my project)
- TypeDecorator is private protected static - like to be able to call that from my Strategy (for now I just copied and pasted into my Strategy)
- FactoryDecorator is private protected static - like to be able to call that from my Strategy (for now I just copied and pasted into my Strategy)

Would you consider opening up some of the extensibility issues above?

**Comment by waynebrantley** [comment]
@khellang If you would accept, I would be happy to do a small PR for some of the above.
If not, I have copied and pasted to have it working - so great job on the library and the extensibility of the DecorationStrategy!

**Comment by khellang** [comment]
Hey @waynebrantley! 👋🏻

Sorry for the late reply. I'd happily take a PR making whatever you need from the registration strategies public, but as discussed in https://github.com/khellang/Scrutor/issues/187, I'd like to avoid making the reflection helpers public. At least as extension methods 😀

**Comment by waynebrantley** [comment]
Ok, this is really all I need!
https://github.com/khellang/Scrutor/pull/193

**Comment by waynebrantley** [comment]
@khellang Any thoughts on the above pr?

**Comment by khellang** [comment]
Sorry @waynebrantley! I'll get a new version out ASAP. Thanks for pinging me again 😅
