### ISSUE TITLE
Add Debug method / way to print list of descriptors

### ISSUE THREAD

**Issue by glen-84** [khellang/Scrutor#198]
```cs
collection.Scan(scan => scan
    .FromAssemblyOf<ITransientService>()
        .AddClasses(classes => classes.AssignableTo<ITransientService>())
            .AsImplementedInterfaces()
            .WithTransientLifetime()
            .Debug() // <-- this.
```

This would write the list of descriptors, with the service name, implementation type, and lifetime, to the console, making it much easier to debug the registration (which can get a lot more complicated than the above example).

**Comment by khellang** [comment]
I don't think this is necessary anymore, as Microsoft has added a ton debugging helpers and `ToString` overrides. It would be trivial to either add this method yourself or just simply loop through the descriptors and write their `ToString` to the console.
