### ISSUE TITLE
Scrutor not working to automatically register the services with the ASP.NET Core DI container in case of .NET 7 application

### ISSUE THREAD

**Issue by santoshpatro** [khellang/Scrutor#201]
Hi Team,

Need help on this issue : https://stackoverflow.com/questions/76080671/scrutor-not-working-to-automatically-register-the-services-with-the-asp-net-core

Thanks,
Santosh

**Comment by khellang** [comment]
Hi @santoshpatro! 👋🏻 

Sorry for the long response time. I see you figured out the issue on StackOverflow, so I'm closing this issue 😊
