### ISSUE TITLE
AOT Compatibility?

### ISSUE THREAD

**Issue by shawnwildermuth** [khellang/Scrutor#203]
Any plans to support CodeGenerator so it has AOT compatibility when .NET 8 comes around? (or are you interested and i'll look at it)?

**Comment by khellang** [comment]
@david-driscoll opened #129 years ago, but unfortunately I haven't had the bandwidth to look at it in detail. It's absolutely something we should revisit and land 😅

**Comment by shawnwildermuth** [comment]
I did this for my [MinimalApiDiscovery/](https://github.com/wilder-minds/MinimalApiDiscovery) and would be happy to take a look here (and defer my project to this one since it's more general purpose). Let me fork it and see what happens.

**Comment by Dreamescaper** [comment]
I have created a small Source Generator for, inspired by Scrutor. Maybe someone will find it useful :)
https://github.com/Dreamescaper/ServiceScan.SourceGenerator
