### ISSUE TITLE
Deadlock while trying to solve wrongly decorated service.

### ISSUE THREAD

**Issue by igorquintaes** [khellang/Scrutor#206]
I ran into this error for some hours while refactoring a code. I mistook an injection when wrote the same interface to be received in the last step from the decoration chain. Would be nice to throw some error in these scenarios, or even scan the injection dependency chain for errors before build the service collection. It could be very helpful to developers find out the error root cause in a shot, mainly inside complex projects.

A small and reproducible code below:

```cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Repro;

public class Program
{
    public static async Task Main(string[] args)
    {
        var host = Host
                .CreateDefaultBuilder(args)
                .ConfigureServices(services => services
                    .AddSingleton<IInjectedClass, AlsoInjectedClass>()
                        .Decorate<IInjectedClass, InjectedClass>())
                .Build();

        host.Services.GetRequiredService<IInjectedClass>(); // <- deadlock here
    }
}

public interface IInjectedClass 
{ }

public class InjectedClass : IInjectedClass
{
    public InjectedClass(IInjectedClass _)
    { }
}

public class AlsoInjectedClass : IInjectedClass
{
    public AlsoInjectedClass(IInjectedClass _) // <- injection error here
    { }
}
```

**Comment by khellang** [comment]
Hello @igorquintaes! 👋🏻 

I think this is an issue for the container itself, i.e. https://github.com/dotnet/runtime/issues/36458 😄
