### ISSUE TITLE
Potential ReflectionTypeLoadException when scanning by assemblies

### ISSUE THREAD

**Issue by daveaglick** [khellang/Scrutor#210]
I've observed an issue where sometimes the call to `Assembly.DefinedTypes` in `TypeSourceSelector.InternalFromAssemblies()` will throw a `ReflectionTypeLoadException` when not all assembly dependencies are currently bound: https://github.com/khellang/Scrutor/blob/a634e5824b0c1e71314259da3855c7845b206384/src/Scrutor/TypeSourceSelector.cs#L157

For example, this seems to be a particular problem in Azure Functions. I've got a local fix that seems to work for me, but I'm not sure what the reasoning for using `DefinedTypes` here is, so wanted to run it by you before proposing a PR. Since we're not using the `TypeInfo` at all, other than to get the actual `Type` anyway, this change ignores types with loading errors. The tradeoff of course is that then you don't get an exception for types that can't be loaded, but I'd personally rather have Scrutor succeed for the types it can load than throw during service registration.

Here's what I would propose:

```csharp
private IImplementationTypeSelector InternalFromAssemblies(IEnumerable<Assembly> assemblies)
{
    return AddSelector(
        assemblies
            .SelectMany(asm =>
            {
                Type[] types;
                try
                {
                    types = asm.GetTypes();
                }
                catch (ReflectionTypeLoadException e)
                {
                    // If there were any loading errors, use the types that were actually loaded
                    types = e.Types;
                }
                return types;
            })
            .Where(x => x != null));
}
```

**Comment by khellang** [comment]
I think it's fine to move away from `TypeInfo` :smile: The library had a lot of `TypeInfo` back in the early .NET Core days. Most of the codebase [was moved away from `TypeInfo` last year](https://github.com/khellang/Scrutor/commit/3ae8fa046a207f39ae28faba93b60df7bc3277ca), but looks like there are some remnants.
