### ISSUE TITLE
Getting types just found during Scan

### ISSUE THREAD

**Issue by dario-l** [khellang/Scrutor#213]
Simply question.

Is there any possibility to take those types just gathered by Scrutor?
I do not want to iterate again.

**Comment by khellang** [comment]
Hey @dario-l! 👋🏻

Not types specifically added by Scrutor, but you can enumerate the descriptors in the service collection to see which types were added.

**Comment by dario-l** [comment]
Hi @khellang again 😃 
Just found a solution. This will work?

```
        var tempServices = new ServiceCollection();

        tempServices.Scan(  );
        
        foreach (var x in tempServices)
        {
            services.Add(x);
        }
```

**Comment by khellang** [comment]
Yes, that will work 👍

**Comment by dario-l** [comment]
Great. Thanks 👍🏻

**Comment by xingzuhui** [comment]
Set do，not single。 services.Add(tempServices.Scan(  )); instead if you can。Never intend to use loop if we don't need。

> Hi @khellang again 😃 Just found a solution. This will work?
> 
> ```
>         var tempServices = new ServiceCollection();
> 
>         tempServices.Scan(  );
>         
>         foreach (var x in tempServices)
>         {
>             services.Add(x);
>         }
> ```
