### ISSUE TITLE
Scrutor stopped working after upgrading to .NET 8

### ISSUE THREAD

**Issue by santoshpatro** [khellang/Scrutor#218]
Hi Khellang,

I am facing an issue with scrutor post .NET 8 upgrade . I have submitted all the details related to the issue at : https://stackoverflow.com/questions/77568822/scrutor-stopped-working-after-upgrading-to-net-8

I also tried to follow this link : https://github.com/khellang/Scrutor/issues/208 , but not sure is there any new version available to fix the issue or any specific code changes are required to get it resolved

Any help on this request is much appreciated

Thanks,
Santosh

**Comment by khellang** [comment]
Hi @santoshpatro!  👋🏻 

I'm not entirely sure how this is related to Scrutor. It seems like something related to a breaking change in SqlClient?

**Comment by xingzuhui** [comment]
But，i think  khellang should update your Scrutor to .net8 .
And supports  keyed registration .
