### ISSUE TITLE
.net 8 version of Scrutor

### ISSUE THREAD

**Issue by Hafeed3s** [khellang/Scrutor#227]
@khellang Is there any .NET 8 version of Scrutor available? I've seen that the branch feature/net8 has been created but there's no pre-release version available

Would be great to have a .NET8 version available as I'm having some `Microsoft.Extensions.DependencyModel` version mismatch issues in my application

Is there any issues migrating to .NET 8 ?

**Comment by Salgat** [comment]
Any chance of creating a .net 8 update that just updates the nugets to 8.x and updates the #ifdefs, until the current more ambitious .net 8 PR is complete?

**Comment by khellang** [comment]
This has been released with v5.0.0. Sorry for the long wait 😔
