### ISSUE TITLE
Signing key shouldn't be public

### ISSUE THREAD

**Issue by bruno-brant** [khellang/Scrutor#229]
I see from #53 that Scrutor only added Strong Naming because a different package wanted it. However, the signing key *must not be public*. Currently, anyone can grab your signing key and sign their own assembly, defeating the whole purpose of strong naming: the idea is to prevent code injection in sensitive scenarios where anyone could grab your code, inject their own malicious code, compile it and replace a valid assembly somewhere with the hacked one. 

I want to make the case that it's preferable to _not_ sign the assembly at all if the key is public/leaked, otherwise people might trust that this is a secure assembly where, in fact, it isn't. 

I'll also create a similar issue in Swashbuckle.AspNetCore.Filters.

**Comment by khellang** [comment]
> However, the signing key must not be public. Currently, anyone can grab your signing key and sign their own assembly

That's the entire point. This is an open source project. Anyone should be able to build it for themselves.

> defeating the whole purpose of strong naming: the idea is to prevent code injection in sensitive scenarios where anyone could grab your code, inject their own malicious code, compile it and replace a valid assembly somewhere with the hacked one.

That's not the purpose of strong naming. It's not a security feature, but an identity feature. See [Microsoft docs](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named).

> I want to make the case that it's preferable to not sign the assembly at all if the key is public/leaked, otherwise people might trust that this is a secure assembly where, in fact, it isn't.

I agree, but for entirely different reasons 😆
