### ISSUE TITLE
Make `IsDecorated` public

### ISSUE THREAD

**Issue by portyanikhin** [khellang/Scrutor#241]
Hello!

Previously, I used `v4.2.2`, and my business logic partially depended on determining whether the service is decorated.
Like this:

```c#
ServiceDescriptor descriptor;
...descriptor.ServiceType is DecoratedType...
```

I can't migrate to `v5.x` right now because the `DecoratedType` class has been removed and I don't see a way to implement such logic.

Is it possible to make the `IsDecorated` extension method (see below) `public`? That would solve my problem.

https://github.com/khellang/Scrutor/blob/e6a329e5aa74a3e9412586fc24bb5c69cc03f207/src/Scrutor/ServiceCollectionExtensions.Decoration.cs#L295

Thanks for such a cool library!

**Comment by khellang** [comment]
> Is it possible to make the `IsDecorated` extension method (see below) `public`? That would solve my problem.

I probably could, yes, but it's trivial to implement yourself 😄

**Comment by portyanikhin** [comment]
> > Is it possible to make the `IsDecorated` extension method (see below) `public`? That would solve my problem.
> 
> I probably could, yes, but it's trivial to implement yourself 😄

I don't dispute that it's a trivial task to implement such a method in your own project. However, I'm sure that this affects the internal Scrutor contract, which may change in the future. Therefore, in my opinion, it's more rational to make this method public. What do you think about this?

Will you merge this PR (https://github.com/khellang/Scrutor/pull/242)?
