### ISSUE TITLE
Sugestion: TryDecorate or Custom Exception when decorate doesn't find the service type

### ISSUE THREAD

**Issue by gravity00** [khellang/Scrutor#28]
Currently, when using decorators, if no `ServiceDescriptor` is found for the type to be decorated, an `InvalidOperationException` [is thrown](https://github.com/khellang/Scrutor/blob/master/src/Scrutor/ServiceCollectionExtensions.Decoration.cs#L171-L174).

That is, at least for me, a good behavior but because the exception is very broad (let's imagine it can be thrown by Scrutor or some other code) there is no way to be sure the exception was due to a missing service type or any other problem. This can be problematic when using a plugin approach, when you may want scan for all libraries in a given directory and to decorate some types, but those types may or may not exist.

My suggestion is to implement a custom exception (ex: `ServiceDescriptorToDecorateNotFoundException` that may even have a property with the type not found) or to add a `TryDecorate` method that returns false if none is found.

**Comment by khellang** [comment]
> My suggestion is to implement a custom exception (ex: `ServiceDescriptorToDecorateNotFoundException` that may even have a property with the type not found) or to add a TryDecorate method that returns false if none is found.

I think we should do both 👍  Are you up for the task? :wink:

**Comment by gravity00** [comment]
@khellang ah yes, I would have made the change myself, but wanted to ask first before making the pull request. I'll need to install VS2017 first.

Question: base class for all `Scrutor` exceptions, or no need?

**Comment by khellang** [comment]
> Question: base class for all Scrutor exceptions, or no need?

I don't think we need a custom base class for all Scrutor exceptions, but it might be nice if the exception derived from `InvalidOperationException`. That way, if someone already catches that exception, we won't break their apps :smile:
