### ISSUE TITLE
Not RC1 compatible

### ISSUE THREAD

**Issue by SharpNoiZy** [khellang/Scrutor#3]
Hi,

it seems that the lib is not 100% RC1 compatible.
I think it has the reason, that you create the solution with Beta 8 and I doesn't start a clean new solution with RC1.
The difference between Beta8 and RC1 solutions are the reference folders named different:
"DNX 4.5.1" -> ".NET Framework 4.5.1"
"DNX Core 5.0" -> ".NET Platform 5.4"

Error message after reference the nuget package in an clean RC1 project:
"The dependency Scrutor 1.1.0 in project MFT.Core does not support framework .NETPlatform,Version=v5.4."
"The dependency Scrutor 1.1.0 in project MFT.Core does not support framework .NETFramework,Version=v4.5.1."

**Comment by khellang** [comment]
> it seems that the lib is not 100% RC1 compatible.

What does this mean? It doesn't install? Doesn't run? What's the problem?

**Comment by SharpNoiZy** [comment]
Sorry have just updated my issue text :)

**Comment by khellang** [comment]
"DNX 4.5.1" is not the same as ".NET Framework 4.5.1", and "DNX Core 5.0" is not the same as ".NET Platform 5.4".

Apparently they've changed the targets for RC1. I'll fix it ASAP. Thanks for filing this! :+1:

**Comment by khellang** [comment]
@SharpNoiZy OK, I've pushed a new version, 1.1.1, that has the new targets; https://github.com/khellang/Scrutor/commit/6a06add5a0ce7daeb83e4160f7130e04fde7e2bb

**Comment by SharpNoiZy** [comment]
Yes, this version works! :+1:
