### ISSUE TITLE
Error - "The non-generic method ...." when using AddTypes [2.0-rc2]

### ISSUE THREAD

**Issue by ppumkin** [khellang/Scrutor#30]
When I try to use the AddTypes as of 2.0rc2 I get the compilation error of below,  when trying to add a type class as per your tests ?

`The non-generic method 'ITypeSelector.AddTypes(params Type[])' cannot be used with type arguments`

I cannot quite understand what the issue is as when I start to make your test code look more like my code it does not complain, but in my project it complains about this. Am I missing a dependency maybe?

When I copied over the TransientService as per your test into my project that worked OK.

When I put my service as the second parameter, and the test TransientService was first the Generic error disappeared. 

I started adding more types I need and some combinations work others do no.

Maybe I am misunderstanding the implementation of this?

My target framework is
 - NETCoreApp1.1

![image](https://cloud.githubusercontent.com/assets/1249683/26343083/903f65d8-3f92-11e7-858d-012cf4d1b482.png)

![image](https://cloud.githubusercontent.com/assets/1249683/26343218/ef99bab0-3f92-11e7-9bfe-56f84aaf1a6c.png)

**Comment by ppumkin** [comment]
I probably should have used more than one type... 

Just to test it out I was using one class quickly but now I have added multiple classes in and the error is gone. I understand this is a compiler error due to your implementaion and me being a bit thick 🤔

**Comment by ppumkin** [comment]
Updated issue. I do not quite understand what the problem is when I added ApplicationSettings

**Comment by khellang** [comment]
@ppumkin The generic `AddTypes` method only have convenience overloads for up to three types. If you want to manually add more types, you need to use the non-generic `params` method:

```csharp
var types = new {

};

services.Scan(scan => scan
    .AddTypes(types)
    .AsImplementedInterfaces()
    .WithTransientLifetime()
);
```

As I'm sure you've discovered, the `AddTypes` method is for manually adding types. If you want to add types from an entire assembly, you can use the `FromAssemblyOf<TType>` method, then filter the types you want to register.

**Comment by ppumkin** [comment]
That is awesome. 👍 
It is just when looking at various DI over the past days it just not obvious anymore how to write somethings. This would be a great addition to your examples? 

Sorry for being a noob 🤕

**Comment by khellang** [comment]
> This would be a great addition to your examples?

Yes. The documentation is currently lacking. Hoping to add some more examples and documentation soon. In the meantime, the tests are probably the best documentation 😉
