### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'Scan' 

### ISSUE THREAD

**Issue by AlexZeitler** [khellang/Scrutor#33]
In a .NET Core App I'm facing this error:

```
Error	CS1061	'IServiceCollection' does not contain a definition for 'Scan' and no extension method 'Scan' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)
```

The code of `ConfigureServices` looks like this:

```csharp
services.Scan(scan => scan
    .FromAssemblies(typeof(MaterialCommandHandler).GetTypeInfo().Assembly)
    .AddClasses(classes => classes.Where(x => {
        var allInterfaces = x.GetInterfaces();
        return
            allInterfaces.Any(y => y.GetTypeInfo().IsGenericType && y.GetTypeInfo().GetGenericTypeDefinition() == typeof(IHandler<>)) ||
            allInterfaces.Any(y => y.GetTypeInfo().IsGenericType && y.GetTypeInfo().GetGenericTypeDefinition() == typeof(ICancellableHandler<>));
    }))
    .AsSelf()
    .WithTransientLifetime()
);
```

I'm using Scrutor 2.0.0.

![image](https://user-images.githubusercontent.com/287480/28502860-c604266a-6ffb-11e7-93a6-61521e69e53d.png)

**Comment by AlexZeitler** [comment]
D'oh: `System.Linq` reference was missing which messed up VS. `dotnet build` has shown the correct error.

**Comment by khellang** [comment]
Glad you figured it out! BTW, `FromAssemblies` can be replaced with `FromAssemblyOf<MaterialCommandHandler>` and the `Where` flause could be replaced with `AssignableToAny(typeof(IHandler<>), typeof(ICancellableHandler<>))`. I just type this on my phone, so can't guarantee that it compiles, but you get the gist :wink:

**Comment by thenewbieprogrammer** [comment]
I am getting the same error. However, System.Linq reference exists

**Comment by khellang** [comment]
Please file a new issue and provide a repro if you want some assistance. I have no idea what to do with the (lack of) information you just provider 😝

**Comment by thenewbieprogrammer** [comment]
Lol, I fixed it, uploading a blog about it...

**Comment by nonoandy** [comment]
> Lol, I fixed it, uploading a blog about it...

url please lol

**Comment by ashikmhd** [comment]
Install [scruter](https://www.nuget.org/packages/Scrutor/)

**Comment by thepirat000** [comment]
You mean [scrutor](https://www.nuget.org/packages/Scrutor/)
