### ISSUE TITLE
Decorator duplicates lifestyle of decorated instance

### ISSUE THREAD

**Issue by dotnetjunkie** [khellang/Scrutor#38]
The `Decorate` method creates a decorator that duplicates the lifestyle of the decorated instance. This means that if a service is a `Singleton`, all its decorators will be `Singleton` as well. There is currently no way to influence that behavior.

It's quite common to have the need to register decorators with a lifestyle lower than their decoratees. For instance, even though the decoratee might be a singleton, its decorator might require a dependency on a scoped service (a DbContext for instance). This requires the decorator to have a lifestyle of scoped or transient.

On top of that, in case there are multiple services that apply to a decorator (when multiple registrations for the same service type exist), and those services have different lifestyles, so will the applied decorators. In other words, a registration for a certain decorator could cause different decorator instances to exist with different lifestyles. This could lead to confusion.

Appart from this, the chosen behavior is very different from what (most) DI Containers do. This could lead to confusion as well and perhaps problems when migrating from Scrutor to a custom DI Container or vice versa.

Is there a particular reason for this behavior?

**Comment by khellang** [comment]
> On top of that, in case there are multiple services that apply to a decorator (when multiple registrations for the same service type exist), and those services have different lifestyles, so will the applied decorators. In other words, a registration for a certain decorator could cause different decorator instances to exist with different lifestyles. This could lead to confusion.

I agree, but this is not the repository to discuss this behavior. This is a result of the ASP.NET Core container allowing different registrations of the same service to have different lifetimes. We just copy the lifetime of the existing registrations. If this is a problem for you, either take it up with the ASP.NET team (which I assume you already have 😝) or just don't add registrations with different lifetimes for the same service 😉 

> Appart from this, the chosen behavior is very different from what (most) DI Containers do.

Again, Scrutor is not a container in itself. We're forced to work within the constraints put in place by the ASP.NET Core container...

> Is there a particular reason for this behavior?

No. It's just never been asked for 😝

**Comment by khellang** [comment]
> The `Decorate` method creates a decorator that duplicates the lifestyle of the decorated instance. This means that if a service is a `Singleton`, all its decorators will be `Singleton` as well. There is currently no way to influence that behavior.

If we introduced a way to influence this behavior, we'd make it much easier to do exactly what you're advocating against below. Sounds like you're requesting something that you're fundamentally opposed to?

**Comment by dotnetjunkie** [comment]
Hi Kristian,

I'm a bit confused. Do you mean that it is impossible for you to apply a decorator with a different lifestyle than its decoratee, because of 'constraints' in the MS container? I wasn't aware of that.

**Comment by khellang** [comment]
> Do you mean that it is impossible for you to apply a decorator with a different lifestyle than its decoratee, because of 'constraints' in the MS container?

No, it's not impossible at all. We can register decorators with whatever lifetimes we want. We just chose to use the lifetime of the decoratee because that sounded like the most logical choice. No one's ever asked for the ability to have different lifetimes from the decoratee.

**Comment by khellang** [comment]
The issues you raised about mixed lifetimes for the same service type etc. is a "feature" of the container itself, and by copying the lifetime of the decoratee, we just "extend" that feature. If we introduced a way to influence this, we'd make it even easier to mix lifetimes for the same service type.

**Comment by dotnetjunkie** [comment]
> If we introduced a way to influence this behavior, we'd make it much easier to do exactly what you're advocating against below. Sounds like you're requesting something that you're fundamentally opposed to?

Do you mean I'm advocating against "having multiple registrations for the same service, with different lifestyles"? My text might have been confusing, but I'm actually _not_ advocating against this. In my experience this is a really common use case and all DI containers (that I know of) do support this.

I would really vote to add this behavior, and further make transient the default lifestyle for a decorator, or make the overloads more explicit, i.e. `DecorateTransient`, `DecorateScoped` and `DecorateSingleton`.

**Comment by khellang** [comment]
> My text might have been confusing, but I'm actually not advocating against this.

Ah, I see. I read

> In other words, a registration for a certain decorator could cause different decorator instances to exist with different lifestyles. This could lead to confusion.

And thought you were against registrations with different lifetimes in general. You just want to ensure all decorators of the same type are registered with the same (specified) lifetime?

> I would really vote to add this behavior, and further make transient the default lifestyle for a decorator, or make the overloads more explicit, i.e. `DecorateTransient`, `DecorateScoped` and `DecorateSingleton`.

I'm sure we can add those overloads, but I'm a little wary about changing the default from copying the decoratee's lifetime to transient (effectively making the default, existing method call `DecorateTransient`).

**Comment by dotnetjunkie** [comment]
> thought you were against registrations with different lifetimes in general.

Not at all. Sometimes it's simply a necessity.

> You just want to ensure all decorators of the same type are registered with the same (specified) lifetime?

When a decorator itself doesn't have any dependencies (except the decoratee of course), and is immutable, it would be fine for the decorator to copy the lifestyle of the decoratee, but giving a decorator its own explicit lifestyle is a more common scenario. In fact, I don't know of any DI Container that allows the decorator to have the lifestyle of the decoratee.

I do think that this "clone lifestyle" behavior is interesting, and I have thought about adding such behavior in the past with Simple Injector in the past, but such "clone lifestyle" behavior would typically only be useful when it considers the lifestyles of _all_ its dependencies, not just the decoratee. For Scrutor to add such "clone lifestyle" behavior is a bit weird, since this is in fact a sort of lifestyle of its own, but in the case of Scrutor, you are only able to use this behavior for decorators, but never for other registrations.

So to me it seems that letting a registered decorator get an explicitly-specified lifetime, is more obvious as default behavior of an API.

**Comment by khellang** [comment]
> In fact, I don't know of any DI Container that allows the decorator to have the lifestyle of the decoratee.

Even if you had explicit control of the lifetime, you could still end up with the decorator having the same lifetime as the decoratee, no?

By copying the lifetime of the decoratee, you at least guarantee that you don't end up with captive dependencies by registering the decorator with a wider lifetime than the decoratee.

> but in the case of Scrutor, you are only able to use this behavior for decorators, but never for other registrations.

Yes, that's true, because it's the only API that depends on existing registrations. That's the only reason it makes sense IMO. All the scanning APIs default to a transient lifetime.

**Comment by dotnetjunkie** [comment]
> you could still end up with the decorator having the same lifetime as the decoratee, no?

Of course. You can for instance register the decoratee _and_ the decorator both as transient.

> you at least guarantee that you don't end up with captive dependencies

Not really. The only thing you prevent is that the decoratee will be a captive dependency, but other dependencies of the decorator might become captive dependencies.

**Comment by khellang** [comment]
Hmm. I just remembered a thing. We don't "clone" anything. We literally replace the decoratee with the decorator in the service collection. Which means there's no way to have a decorator and a decoratee with different lifetimes.

**Comment by dotnetjunkie** [comment]
> Which means there's no way to have a decorator and a decoratee with different lifetimes.

I'm a bit confused by this statement. When looking the [following code](https://github.com/khellang/Scrutor/blob/master/src/Scrutor/ServiceCollectionExtensions.Decoration.cs#L316):

``` c#
private static ServiceDescriptor WithFactory(this ServiceDescriptor descriptor, 
    Func<IServiceProvider, object> factory)
{
    return ServiceDescriptor.Describe(descriptor.ServiceType, factory, descriptor.Lifetime);
}
```
We see that the `ServiceDescriptor.Describe` method is called with the `Lifetime` of decoratee. 

It seems to me that it could be easily replaced with `ServiceLifetime.Transient` for instance.

Or am I missing something?

**Comment by khellang** [comment]
> It seems to me that it could be easily replaced with ServiceLifetime.Transient for instance.

Yes, but that would replace the existing registration:

https://github.com/khellang/Scrutor/blob/74557a80b434c4d3c1eb6a57c0055c249a569d69/src/Scrutor/ServiceCollectionExtensions.Decoration.cs#L281-L289

When calling `Decorate<T>`, we don't *add* a new registration, we take the existing registration and *replace it*, which means it must have the existing lifetime.

Consider this:

```csharp
var services = new ServiceCollection();

services.AddSingleton<IDecoratee, Decoratee>();

services.Decorate<IDecoratee, Decorator>(); // Or imagine this being `DecorateTransient`

var provider = services.BuildServiceProvider();

var a = provider.GetRequiredService<IDecoratee>();
var b = provider.GetRequiredService<IDecoratee>();
```

Would `a` and `b` be the same instance? When you added the service as a singleton, it would be very weird if it weren't...

**Comment by dotnetjunkie** [comment]
Ah, I see. What you are saying is that giving the decorator a shorter lifetime than its decoratee, might cause the decorator to become a [Captive Dependency](http://blog.ploeh.dk/2014/06/02/captive-dependency/) when injected into a consumer.

This is absolutely correct, but on the other hand, as we discussed above, keeping the decorator's lifestyle in sync with that of its decoratee will cause Captive Dependencies as well, in case the decorator takes a dependency on other services (other than the decoratee) that have a shorter lifetime than the decoratee.

The difference is, by fixing the lifestyle of the decorator, it will be impossible for the user to fix a Captive Dependency when it occurs, while when it occurs with the configurable lifestyle, we actually have the ability to fix the problem.

That said, in either case, it is important to have some tooling that detects Captive Dependencies for us. Both Microsoft.Extensions.DependencyInjection, Autofac, Castle Windsor and Simple Injector do detect these problems (although with MS you will have to explicitly configure the container to do so).

**Comment by julealgon** [comment]
> We can register decorators with whatever lifetimes we want. We just chose to use the lifetime of the decoratee because that sounded like the most logical choice. 

It is far from logical IMHO. It is extremely common as @dotnetjunkie mentioned to have a decorator with a shorter lifetime than the decoratee itself, _especially_ when the decorator has dependencies that are also short-lived. Cloning the decoratee lifetime drastically increases the chance of captive dependencies in this scenario.

Having all decorators be transient by default would make a lot more sense.

> No one's ever asked for the ability to have different lifetimes from the decoratee.

Can I be added to that list? The fact that the lifetime is cloned completely prohibits core scenarios, so it would invalidade the feature to me.

Yet, I'm still a bit confused by the discussion here... is it possible to implement what Steven suggested there, something like:
- `DecorateTransient`
- `DecorateSingleton`
- etc
?

Considering this issue has not been closed yet I assume it should be possible.

**Comment by khellang** [comment]
I guess you didn't see my comment about not being able to do this?

> Hmm. I just remembered a thing. We don't "clone" anything. We literally replace the decoratee with the decorator in the service collection. Which means there's no way to have a decorator and a decoratee with different lifetimes.

You can argue with me all you want, but it won't make Microsofts container implementation any better. I suggest you try arguing with them or just go use SimpleInjector, which has all this figured out already 🤔

**Comment by julealgon** [comment]
> I guess you didn't see my comment about not being able to do this?

I did but I was just confused as at one point it seemed doable. Can you close this issue if there is no further work though?

> You can argue with me all you want, but it won't make Microsofts container implementation any better.

Not really trying to argue with you, just trying to understand why we can't do it. Your explanation made sense, so thanks for that.

> I suggest you try arguing with them or just go use SimpleInjector, which has all this figured out already 🤔

Do you know exactly which kind of extension point would be needed to make decorators work without overwriting registrations like you do today? I feel like it should be possible to ask for an extension point without breaking existing functionality and without overengineering the standard container.

**Comment by khellang** [comment]
> I feel like it should be possible to ask for an extension point without breaking existing functionality and without overengineering the standard container.

No, that's what makes this so hard. There's no way to add any functionality to the existing container without breaking people. See all the existing (rejected) issues about decoration in the DI repo.

**Comment by dotnetjunkie** [comment]
Kristian is completely right. This is the core problem with DI in .NET Core: It is the built-in Container that defines the DI abstraction. Adding features to the built-in container means the abstraction is changed. And changing the abstraction means breaking everybody.
