### ISSUE TITLE
Is there the ability to detect already registered classes/interfaces and not override them?

### ISSUE THREAD

**Issue by ckapatch** [khellang/Scrutor#41]
Thank you for an incredible library, really appreciate it!

We have a situation where we're creating a bootstrapping library internally to handle most of our setup for a core web api library so that we can quickly spin up web api projects without having to do a lot of configuration/setup. 

The bootstrapping library contains this library and runs a call to register classes from the web api library as such:
```
services.Scan(scan => scan
	.FromAssemblies(assemblies)
	.AddClasses()
	.AsImplementedInterfaces()
	.WithTransientLifetime());
```

This is called in the Startup.cs class as a static call:

```
public void ConfigureServices(IServiceCollection services)
{
  // Internal        

  Bootstrapping.Configure(services);

  //add additional services
}
```

The problem here is if a developer puts their additional services first, the above code will override that service. 

Is there a way to detect if a service has been loaded and skip that registration?
Thanks!

**Comment by khellang** [comment]
Hi Chad!

I'm glad you've found the library useful -- despite the poor documentation 😝

As a matter of fact, there is the concept of a `RegistrationStrategy`, contributed by the awesome @adamhathcock back in #22.

This test should show you how it's called:

https://github.com/khellang/Scrutor/blob/553e655d02282913f94a4ebf30112932ecb062ab/test/Scrutor.Tests/ScanningTests.cs#L47-L63

Notice the call to `.UsingRegistrationStrategy(RegistrationStrategy.Skip)`. I think that should do what you'd expect :smile:

**Comment by khellang** [comment]
Looking at it now, I think it would be better if it was named `SkipExisting` or something, but the XML docs should explain what it does:

https://github.com/khellang/Scrutor/blob/553e655d02282913f94a4ebf30112932ecb062ab/src/Scrutor/RegistrationStrategy.cs#L8-L11

**Comment by ckapatch** [comment]
Hey @khellang Thank you very much. Who likes writing documentation, can't blame you there. This looks perfect! Thanks for the quick response.

Chad

**Comment by khellang** [comment]
@ckapatch Did you get it working? I'm closing this issue as there doesn't seem to be anything actionable here (except better documentation 😝 )
