### ISSUE TITLE
MissingTypeRegistrationException is thrown when decorating open generic registered types

### ISSUE THREAD

**Issue by julealgon** [khellang/Scrutor#49]
Suppose I have a very simple generic interface as below:
```
interface IGeneric<T>
{
    void DoSomething(T value);
}
```

I then add a generic implementation that is then registered using open generics syntax:
```
class Generic<T> : IGeneric<T>
{
    public void DoSomething(T value)
    {
        Console.WriteLine("Something");
    }
}

...

services.AddTransient(typeof(IGeneric<>), typeof(Generic<>));
```

When I try to decorate this inteface for a specific type, I get an exception:
```
services.Decorate<IGeneric<int>, GenercDecorator<int>>();
```

Throws:
> **Scrutor.MissingTypeRegistrationException:** 'Could not find any registered services for type '`IGeneric<int>`'.'

This completely kills a few real world scenarios for my use case, as I want to provide a standard implementation by default, but have specific decorators for specific model types.

To work around this I'd have to scan all possible types and register the `IGeneric` for each of them, which is just not practical and will outright now work for some cases where you can't know the T for all use cases.

EDIT: 
Found a somewhat similar issue raised by Steven (@dotnetjunkie): #39

My scenario is slightly different in that I'm not requesting generic decorators, but closed decorators on top of generic registrations.

Is it possible to make what I want to work with the existing constraints?

I have to say though... reading the outcome of #39 makes me quite sad. Open generic decorators are a killer feature, so now I'm also reconsidering using this default container.

**Comment by julealgon** [comment]
> You could try raising (yet another) issue over at Microsoft...

Do you mean we already have issues related to this limitation raised to them? Can you link them here for visibility?

**Comment by khellang** [comment]
There are many issues related to decoration in the DI repo. Most of the predate this project (there's a reason this project even exist 😉). I'm on my phone, so it would probably be easier and quicker for you to do a search for "decorate" in the aspnet org.
