### ISSUE TITLE
Upgrade to the latest microsoft.extensions.dependencyinjection version?

### ISSUE THREAD

**Issue by khteh** [khellang/Scrutor#50]
Hi;
   The latest scrutor version still references 1.1.0 of microsoft.extensions.dependencyinjection. When can it upgrade to reference the latest version 2.0.0? Thanks!

**Comment by khellang** [comment]
Just update your reference to 2.0.0? I don't think there should be any incompatibilities.

**Comment by khteh** [comment]
There are incompatibilities. I have to use assembly redirect in app.config

**Comment by khellang** [comment]
What are the incompatibilities?

**Comment by khteh** [comment]
Can't remember now. Either build time or runtime error.

**Comment by khellang** [comment]
I'd love to know, cause I'd like to avoid bumping the dependency and releasing a new version, leaving everyone using 1.x behind, for no benefit (other than not having to pin the MS.Ext.DI dependency to 2.0).

**Comment by khteh** [comment]
You can try with your unit test project referencing higher version of the
library and see if you bump into the error. Otherwise wait until tomorrow i
get back to the office.

**Comment by jbogard** [comment]
Just leave all the 1.x people behind....netstandard 1.x is dead....

**Comment by khellang** [comment]
v3.0.0 is now [on NuGet](https://www.nuget.org/packages/Scrutor/3.0.0) :smile:
