### ISSUE TITLE
Generic type decorators

### ISSUE THREAD

**Issue by LittleColin** [khellang/Scrutor#52]
Is it possible to register the following (assuming MyRepositoryA and MyRepositoryB already registered as implemented intefaces)?
`
services.AddSingleton<IRepositoryFactory<IMyRepositoryA>, RepositoryFactory<IMyRepositoryA>>();
services.AddSingleton<IRepositoryFactory<IMyRepositoryB>, RepositoryFactory<IMyRepositoryB>>();
`
etc.

- and of course, thanks for the library!

**Comment by khellang** [comment]
Have you tried? 😝

**Comment by LittleColin** [comment]
I should have made my question more specific - is it possible to make use of either the decorator or scan to automatically find types matching a criteria (e.g. under Co.Repositories namespace) and wrap these without having to register each one individually?

e.g. something like:

```
services.Scan(scan => scan
                .FromAssemblyOf<IMyRepositoryA>()
                .AddClasses(c => c.InNamespaceOf<IMyRepositoryA>())
                .AsGenericInstance<RepositoryFactory>()
                .WithGenericInterface<IRepositoryFactory>()
                .WithSingletonLifetime());
```

**Comment by khellang** [comment]
Oh, are you asking if you can register open generics? I.e.

```csharp
services.AddSingleton(typeof(IRepositoryFactory<>), typeof(RepositoryFactory<>))
```

That's possible without this library.

**Comment by khellang** [comment]
If you're asking if it's possible to scan and register open generic types, then it's a no. It's not possible.

**Comment by LittleColin** [comment]
Yes it was the latter - scan and register open generic types. But as you point out, that is not necessary if registering open generics using the syntax you showed. I wasn't aware this was possible so thanks for your help on this - feel free to close the issue, it's no longer an issue for me.

Thanks again
