### ISSUE TITLE
Documentation for Decoration?

### ISSUE THREAD

**Issue by dradovic** [khellang/Scrutor#54]
Would you mind documenting a little bit how the decoration feature works? Can you maybe provide an example of a decoration and how to get the decorating service?

From #14 I can do a lot of guessing but I think it would be still nice to have some documentation or maybe another blog on your site (like you did [here](https://kristian.hellang.com/introducing-scrutor/)).

**Comment by khellang** [comment]
Cool. There's not much to it, which is why I haven't been too fuzzed about providing extensive documentation. Glad you found it useful!
