### ISSUE TITLE
.As(...) forgets the previous calls to .As*()

### ISSUE THREAD

**Issue by dradovic** [khellang/Scrutor#55]
I've noticed that if I change the order of my `As*` calls, I get different results.

For example: the following code works as expected:

        private static ILifetimeSelector AsSelfAndMatchingInterfacesAndDeclaredServiceTypes(this IServiceTypeSelector selector)
        {
            return selector
                .As(t =>
                {
                    // some types are selected here
                })
                .AsSelf()
                .AsMatchingInterface();
        }

while this code does NOT:

        private static ILifetimeSelector AsSelfAndMatchingInterfacesAndDeclaredServiceTypes(this IServiceTypeSelector selector)
        {
            return selector
                .AsSelf()
                .AsMatchingInterface()
                .As(t =>
                {
                    // some types are selected here
                });
        }

**Comment by khellang** [comment]
Yeah, I've never encountered a scenario where I've needed several, so it's definitely not a supported scenario. The fact that some combinations work is purely accidental. I'll have to take a look to see if I can work it in somehow 😊

**Comment by dradovic** [comment]
I'm glad you're looking to this. I need to cover all three scenarios: I want the selected classes to be registering as themselves, and a matching interface, and possibly more interfaces that are listed as a custom attribute.

Let me know if there's anything I can do to further assist you.

**Comment by khellang** [comment]
Hmm. I actually think this should be supported (it's been a while since I touched that part of the code base 😝).

I just can't seem to reproduce a problem. I tried running the following two tests:

```csharp
[Fact]
public void CanRegisterUsingMultipleAsCalls()
{
    Collection.Scan(scan => scan.FromAssemblyOf<ITransientService>()
        .AddClasses(t => t.AssignableTo<IDuplicateInheritance>())
        .As(t => new[] { typeof(IOtherInheritance) })
        .AsMatchingInterface()
        .AsSelf());

    Assert.Collection(Collection,
        t => Assert.Equal(typeof(IOtherInheritance), t.ServiceType),
        t => Assert.Equal(typeof(IDuplicateInheritance), t.ServiceType),
        t => Assert.Equal(typeof(DuplicateInheritance), t.ServiceType));
}

[Fact]
public void CanRegisterUsingMultipleAsCallsReverseOrder()
{
    Collection.Scan(scan => scan.FromAssemblyOf<ITransientService>()
        .AddClasses(t => t.AssignableTo<IDuplicateInheritance>())
        .AsSelf()
        .AsMatchingInterface()
        .As(t => new[] { typeof(IOtherInheritance) }));

    Assert.Collection(Collection,
        t => Assert.Equal(typeof(DuplicateInheritance), t.ServiceType),
        t => Assert.Equal(typeof(IDuplicateInheritance), t.ServiceType),
        t => Assert.Equal(typeof(IOtherInheritance), t.ServiceType));
}
```

And both pass with flying colors. Of course, the order is different, but that should be expected. The registrations are made in the order you call the methods.

You say "I get different results", can you expand a bit on that? What are you seeing that you weren't expecting?

**Comment by dradovic** [comment]
I was so vague in my description because I wasn't really analyzing what was going on. If I remember correctly, in my first order, it simply didn't work and when I turned it around - it worked. That's when I entered this issue. But I can for sure have a closer look and report more. The only thing is that I'm on holidays now, so it might take a while until I get back to it. So please hang on.

**Comment by dradovic** [comment]
Unfortunately I’m traveling at the moment without access to a programming environment. Might take a while until I get back to this.

**Comment by dradovic** [comment]
Okay. So finally I've found the time to play more with it. What happens in my project is this: the dependency is still found (i.e. the type is selected) when I reverse the order, but the types selected in the previous .As(*) calls lose their scope information.

In my code, I configure the dependencies like this:

        public static void AddConventionalServices(this IServiceCollection services)
        {
            Assembly callingAssembly = Assembly.GetCallingAssembly();
            services.Scan(scan =>
            {
                scan.FromAssemblies(...)
                    .AddClasses(classes => classes.WithoutAttribute<SingletonServiceAttribute>()
                                                  .WithoutAttribute<ScopedServiceAttribute>()
                                                  .WithoutAttribute<TransientServiceAttribute>()
                                                  .Where(t => t.Name.EndsWith("Service") || t.Name.Contains("Repository")))
                        .AsSelfAndMatchingInterfacesAndDeclaredServiceTypes().WithScopedLifetime();
            });
        }

With the following code the service (which implements a matching interface) is scoped:

        private static ILifetimeSelector AsSelfAndMatchingInterfacesAndDeclaredServiceTypes(this IServiceTypeSelector selector)
        {
            return selector
                .As(t =>
                {
                    return new Type[] { t };
                })
                .AsMatchingInterface();
        }

But in the reverse order, it is not anymore:

        private static ILifetimeSelector AsSelfAndMatchingInterfacesAndDeclaredServiceTypes(this IServiceTypeSelector selector)
        {
            return selector
                .AsMatchingInterface()
                .As(t =>
                {
                    return new Type[] { t };
                });
        }

So I believe it's not only about the .As(*) methods but the conjunction with the With(*) extension methods.

Side note:
I would have like to extend your code-base and show you the issue there with a corresponding unit test, however I wasn't able to compile the solution on my Ubuntu box (of course only targeting .NET Core). If you are interested we can work on this in a separate issue.

**Comment by khellang** [comment]
I'll take another look when I find some time 👍

> I wasn't able to compile the solution on my Ubuntu box

I think that might be because I also target .NET Framework. If you want to build everything, I think you need Mono installed. Otherwise you have to pass the framework explicitly when building.
