### ISSUE TITLE
Possible to register as matching interface OR as self?

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [khellang/Scrutor#69]
Suppose I have the following services:
```c#
[Service]
public class FooService : IFooService
{
...
}
```
and
```c#
[Service]
public class BarService
{
...
}
```

Then:
```c#
serviceCollection.Scan(scan => scan.FromApplicationDependencies()
    .AddClasses(classes => classes.WithAttribute<ServiceAttribute>())
    .AsMatchingInterface()
    .AsSelf()
    .WithSingletonLifetime()
);
```
registers `FooService` two times:  as `IFooService` and as `FooService`.

Is it possible to have a selector that tries to register it as the matching interface, and only if it can't find one, registers it as self? 

So in the example above `FooService` will be registered only as `IFooService` and `BarService` will be registered as `BarService`.

**Comment by khellang** [comment]
It's possible, but you'd have to write the logic yourself. It should be pretty trivial to just copy the code from `AsMatchingInterface` and `AsSelf` and write your own extension method. I wouldn't know what to call it though...

**Comment by Jaap-van-Hengstum** [comment]
Thanks. I'll try that.
