### ISSUE TITLE
Scrutor crashes ASP.NET 5 RC1 on startup

### ISSUE THREAD

**Issue by mdmoura** [khellang/Scrutor#7]
Hello,

I am using Scrutor to configure MediatR (https://github.com/jbogard/MediatR) on an ASP.NET 5 RC1 application. On Startup I have:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(MessageGetQueryHandler))
        .AddClasses()
        .AsImplementedInterfaces());

The class MessageGetQueryHandler is just a handler in the project so I can target the assembly:

      public class MessageGetQueryHandler : IRequestHandler<MessageGetQuery, MessageGetModel> {
      }

When I run the application DNX just stops and exits. The only thing I can see is a few "Cannot find or open the PDB file." messages on the Output ...

I then tried the following:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Startup))
        .AddClasses()
        .AsImplementedInterfaces());

Same problem here ... Then I tried:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator))
        .AddClasses()
        .AsImplementedInterfaces());

Now it runs, I am able to inject IMediator but not the Handlers since I am not scanning the project assembly ...

Any idea what might be wrong?

Thank You,
Miguel

**Comment by khellang** [comment]
Hey!

Do you have a more stack trace so I can take a look?

I'm pretty sure there's little I can do about this in Scrutor. It's probably something in DNX acting up :disappointed:

**Comment by mdmoura** [comment]
I think I was able to narrow the problem ... 

One of the classes I have on my project is the following:

    public class Response<T> : IResponse<T> {
      public IPaging Paging { get; private set; }
      public IList<T> Result { get; private set; }

      public Response() { } 
    }

When I use:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Startup))
        .AddClasses()
        .AsImplementedInterfaces());

I get the error:

System.ArgumentException: Cannot instantiate implementation type 'MvcProject.Response`1[T]' for service type 'MvcProject.IResponse`1[T]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceTable..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

I have no error anymore if I use the following:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Startup))
        .AddClasses());

How to solve this? 

Thank You,
Miguel

**Comment by adamhathcock** [comment]
I think this is because it registers the open generic type with the implemented interfaces and doesn't know how to create it later.

Are you asking for a closed type to be injected somewhere?

A simple fix would be to filter out generics when using as implemented.

**Comment by mdmoura** [comment]
I tried something like that but I keep getting an error. So I have the configuration:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Startup))
          .AddClasses(y => 
            y.AssignableTo<IMediator>()).AsImplementedInterfaces().WithSingletonLifetime()
          .AddClasses(y => {
            y.AssignableTo(typeof(IEnvelope<>));
            y.AssignableTo(typeof(IRequest));
            y.AssignableTo(typeof(IAsyncRequest));
            y.AssignableTo(typeof(IRequest<>));
            y.AssignableTo(typeof(IAsyncRequest<>));
            y.AssignableTo(typeof(IRequestHandler<,>));
            y.AssignableTo(typeof(IAsyncRequestHandler<,>));
            y.AssignableTo(typeof(INotificationHandler<>));
            y.AssignableTo(typeof(IAsyncNotificationHandler<>));
          }).AsImplementedInterfaces().WithTransientLifetime());

Then I have the following controller:

    public class MessageApiController : Controller {
        private readonly IMediator _mediator;
        public MessageApiController(IMediator mediator) {
          _mediator = mediator; 
        }
        [HttpGet("messages")]
        public async Task<IActionResult> Get(MessageGetApiModel.Query query) {
          IEnvelope<MessageGetApiModel.Reply> reply = await _mediator.SendAsync(query);     
          return Ok(reply); 
        }
    }

And in my application I have the following:

      public interface IEnvelope<T> {
        IPaging Paging { get; }
        IList<T> Result { get; }    
      }

      public class Envelope<T> : IEnvelope<T> {
        public Envelope() { } // Envelope
      }

      public class MessageGetApiModel {
        public class Query : IAsyncRequest<IEnvelope<Reply>> {
           // Query properties      
        }
        public class Reply {
           // Reply properties
        }   
      }

      public class MessageGetApiModelHandler : IAsyncRequestHandler<MessageGetApiModel.Query, IEnvelope<MessageGetApiModel.Reply>> {

        public MessageGetApiModelHandler() {
        }

        public async Task<IEnvelope<MessageGetApiModel.Reply>> Handle(MessageGetApiModel.Query query) {
          // Handle code
        }
      }

When I access the URL I got the error:

    An unhandled exception occurred while processing the request.
    InvalidOperationException: No service for type 'MediatR.IAsyncRequestHandler`2[MVCTest.MessageGetApiModel+Query,MVCTest.IEnvelope`1[MVCTest.MessageGetApiModel+Reply]]' has been registered.

    Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
    InvalidOperationException: Handler was not found for request of type MVCTest.MessageGetApiModel+Query.
    Container or service locator not configured properly or handlers not registered with your container.
 
    MediatR.Mediator.GetHandler(Object request, Type handlerType)

I don't see I am missing something on my services configuration using Scrutor ... Am I?

Thank You,
Miguel

**Comment by adamhathcock** [comment]
With the way you're registering, it expects IAsyncRequestHandler to be registered as an open generic. You don't have any classes using it as an open generic.  MessageGetApiModelHandler uses the interface as a closed generic which isn't registered.

**Comment by mdmoura** [comment]
@adamhathcock, sorry, not sure what to change after your comment. I was using Autofac and the configuration was registering the handlers and using them the same way ...

Could you, please, point what should I change in my configuration?

Thank You

**Comment by adamhathcock** [comment]
Instead of using IAsyncRequestHandler<,> in the AssignableTo, try using IAsyncRequestHandler<MessageGetApiModel.Query, IEnvelope<MessageGetApiModel.Reply>>

The functionality of AssignableTo could be changed to understand generics better to register types the way you want.

**Comment by adamhathcock** [comment]
Actually, I take back what I said.  Looks like there is a test doing what you want: https://github.com/khellang/Scrutor/blob/master/test/Scrutor.Tests/ScanningTests.cs#L81

I'm not sure why.  I'd have to run the code which I won't have a chance until Monday even then I may not have time.

**Comment by mdmoura** [comment]
@adamhathcock, yes I tried that but it does not compile ...

Here is the definition of IAsyncRequestHandler:
https://github.com/jbogard/MediatR/blob/c6bb0f42fdb7f860c3824ea88f033ea8695234ce/src/MediatR/IAsyncRequestHandler.cs

**Comment by adamhathcock** [comment]
I think you're going to have to give an example more outside of your actual codebase.  Or have a branch with this setup to allow debugging.

I do this and things work:

```
[Fact]
public void AutoRegisterAsMatchingInterface2()
{
	var collection = new ServiceCollection();

	collection.Scan(x => x.FromAssembliesOf(typeof(IAsyncRequest<>)).AddClasses(y =>
																				{
																					y.AssignableTo(typeof(IAsyncRequestHandler<,>));
																				}).AsImplementedInterfaces().WithTransientLifetime());

	var sp = collection.BuildServiceProvider();
	var q = sp.GetRequiredService<IAsyncRequestHandler<MessageGetApiModel.Query, IEnvelope<MessageGetApiModel.Reply>>>();
}

public interface IEnvelope<T>
{
	string Paging
	{
		get;
	}
	IList<T> Result
	{
		get;
	}
}

public class Envelope<T> : IEnvelope<T>
{
	public Envelope()
	{
	} // Envelope

	public string Paging { get; }
	public IList<T> Result { get; }
}

public class MessageGetApiModel
{
	public class Query : IAsyncRequest<IEnvelope<Reply>>
	{
		// Query properties      
	}
	public class Reply
	{
		// Reply properties
	}
}

public class MessageGetApiModelHandler : IAsyncRequestHandler<MessageGetApiModel.Query, IEnvelope<MessageGetApiModel.Reply>>
{

	public MessageGetApiModelHandler()
	{
	}

	public Task<IEnvelope<MessageGetApiModel.Reply>> Handle(MessageGetApiModel.Query query)
	{
		throw new NotImplementedException();
	}
}

public interface IAsyncRequestHandler<Q, E>
{
}

public interface IAsyncRequest<E>
{
}
```

**Comment by mdmoura** [comment]
I created a ASP.NET Core web application as example to replicate the problem:
https://github.com/mdmoura/AspCoreIoc

The application includes a Ping handler ... Just access http://localhost:5000/ping.

The Startup.cs is: https://github.com/mdmoura/AspCoreIoc/blob/master/src/AspCoreIoc/Startup.cs

Check the following lines:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Ping))
        .AddClasses(y => {
          y.AssignableTo(typeof(IMediator));
          //y.AssignableTo(typeof(IRequest<>));
          //y.AssignableTo(typeof(IRequestHandler<,>));
        }).AsImplementedInterfaces().WithScopedLifetime());

With this I am able to inject IMediator but, of course, not the Handlers. Then try:

      services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Ping))
        .AddClasses(y => {
          y.AssignableTo(typeof(IMediator));
          y.AssignableTo(typeof(IRequest<>));
          y.AssignableTo(typeof(IRequestHandler<,>));
        }).AsImplementedInterfaces().WithScopedLifetime());

In this case not even the Mediator is added to the services list. Strange, isn't it?

Does this help?

**Comment by khellang** [comment]
@mdmoura That's because for each method you're calling on the class filter, you're restricting the set of types, so you're effectively trying to register classes that are assignable to `IMediator` **and** `IRequest<>` **and** `IRequestHandler<,>`. Of course, there are no classes that satisfies these constraints.

**Comment by khellang** [comment]
I'm not really sure what this issue is about anymore. It seems we're way past the "Cannot find or open the PDB file." errors at this point.

If you're looking for a working setup for MediatR, I suggest you look at the (working) [sample in the MediatR repo](https://github.com/jbogard/MediatR/blob/283c00707234ccc37eebff0cf78db39b31dd5c2e/samples/MediatR.Examples.AspNetCore/Program.cs#L28-L31).

**Comment by mdmoura** [comment]
@khellang true, the IRequest<T> is not necessary ...

Now I understand what I was doing wrong ... Maybe adding that info in the docs would be useful for future reference. It is not something obvious as the configuration of some IoC out there are not like this ...

**Comment by khellang** [comment]
@mdmoura Can you point me to a container that has conventions like that that doesn't function this way? I'd :heart: to see it :smile:

**Comment by mdmoura** [comment]
I think the sintax of Autofac makes maybe a little bit more sense. What about:
    .Register(typeof(IMediator))).AsImplementedInterfaces().WithScopedLifetime()

I think the AddClasses with the lambda expression could be an option?

Just an idea ... To be honest I might be to used to other type of configuration and missed that detail.

**Comment by adamhathcock** [comment]
I might play around with linking in the AssignedTo with more fluent interfaces.  I have to admit I was confused too.

I like this project and need something like it so I want to keep helping :)

**Comment by khellang** [comment]
@mdmoura @adamhathcock If you did the following;

```csharp
var result = new[] { "hello", "hello world", "hello adam", "hello hello" }
    .Where(x => x.StartsWith("hello"))
    .Where(x => x.EndsWith("hello"))
    .ToArray();
```

What would you expect `result` to be?

 1. ["hello", "hello hello"]
 2. ["hello", "hello world", "hello adam", "hello hello"]

**Comment by adamhathcock** [comment]
Of course it should be the first as that's how LINQ works.  It does AND.

I think @mdmoura and I was tripped up by being able to do:

```
services
    .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Ping))
    .AddClasses(y => {
      y.AssignableTo(typeof(IMediator));
      y.AssignableTo(typeof(IRequest<>));
      y.AssignableTo(typeof(IRequestHandler<,>));
    }).AsImplementedInterfaces().WithScopedLifetime());
```

Like you said, it will behave by AND here.  Without actually trying to code, I think it should be more like:

```
services
    .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Ping))    .AddClasses.Where.AssignableTo(typeof(IMediator)
).AsImplementedInterfaces().WithScopedLifetime());
```

Something like that wouldn't allow multiple AssignableTo clauses after AddClasses.  Just adjusting the fluent interfaces to disallow some things might help.

**Comment by khellang** [comment]
> Of course it should be the first as that's how LINQ works. It does AND.

Well, it's obvious to you because you _know_. Now you know that Scrutor's `AddClasses` filter is additive as well :wink:

> Something like that wouldn't allow multiple AssignableTo clauses after AddClasses. Just adjusting the fluent interfaces to disallow some things might help.

"Just adjusting". You want each and evey method for filtering to be on its own interface, and then have n combinations of those? What if you also wanted to filter by namespace there? Would that still be possible? Having loads and loads of fluent interfaces for this kind of thing is, IMO, more overhead than the value it provides.

**Comment by adamhathcock** [comment]
I don't think it would be a lot of overhead.  If I get sometime, I may do a PR for some things.

It's not a big deal to me.  Just thought it might help people as there are a good number of options when registering types.

**Comment by mdmoura** [comment]
@khellang I am not saying that your interpretation of how LINQ works is wrong but it is easy to miss the behavior when looking at:

    services
        .Scan(x => x.FromAssembliesOf(typeof(IMediator), typeof(Ping))
        .AddClasses(y => {
          y.AssignableTo(typeof(IMediator));
          y.AssignableTo(typeof(IRequestHandler<,>));
        }).AsImplementedInterfaces().WithScopedLifetime());

**Comment by khellang** [comment]
@mdmoura No, becuase just as I know LINQ does additive filtering, I know that Scrutor does the same, so it's immediately obvious to me that you're looking for types assignable to both `IMediator` **and** `IRequestHandler<,>` :smile:

I just don't see a solution to this, other than education. You might actually *want* to find types that are assignable to two different interfaces. Yes, I know it's a weird requirement, but I've gone with maximum flexibility here. Given enough rope and all that... I think this just needs to be documented in some way. I don't think there's any point in being too smart and limiting the use cases of this library.

**Comment by mdmoura** [comment]
@khellang Yes, that is why my first suggestion was "Maybe adding that info in the docs would be useful for future reference." because I knew that it is a normal Linq behavior but it is not something that is obvious by reading "AssignableTo(..); AssignableTo(..); ", see? Just that, for as far as me now I know what it is doing so no problem there ... :-)
