### ISSUE TITLE
Decorate extension much slower than lambda decorator

### ISSUE THREAD

**Issue by myshon** [khellang/Scrutor#73]
Out of curiosity, I did some performance tests of `Decorate` method. Here are tests classes

```
public interface IRepository
{
    int Save();
}

public class Repository : IRepository
{
    public int Save()
    {
        return 1;
    }
}

public class CachedRepository : IRepository
{
    private readonly IRepository repository;

    public CachedRepository(IRepository repository)
    {
        this.repository = repository;
    }

    public int Save()
    {
        return 1;
    }
}

public class CachedRepositoryWithImpl : IRepository
{
    private readonly Repository repository;

    public CachedRepositoryWithImpl(Repository repository)
    {
        this.repository = repository;
    }

    public int Save()
    {
        return 1;
    }
}
```
and benchmark class (using BenchmarkDotNet)

```
public class DecorateTests
{
    private const int N = 1000000;

    private readonly IServiceProvider manualProvider;
    private readonly IServiceProvider decorateProvider;
    private readonly IServiceProvider lambdaProvider;

    public DecorateTests()
    {
        var manualCollection = new ServiceCollection();
        manualCollection.AddTransient<Repository>();
        manualCollection.AddTransient<IRepository, CachedRepositoryWithImpl>();
        manualProvider = manualCollection.BuildServiceProvider();
        
        var decorateCollection = new ServiceCollection();
        decorateCollection.AddTransient<IRepository, Repository>();
        decorateCollection.Decorate<IRepository, CachedRepository>();
        decorateProvider = decorateCollection.BuildServiceProvider();
        
        var lambdaCollection = new ServiceCollection();
        lambdaCollection.AddTransient<Repository>();
        lambdaCollection.AddTransient<IRepository>(provider => new CachedRepository(provider.GetService<Repository>()));
        lambdaProvider = lambdaCollection.BuildServiceProvider();
    }

    [Benchmark]
    public void Decorate()
    {
        var instance = decorateProvider.GetService<IRepository>();
    }

    [Benchmark]
    public void LambdaDecorator()
    {
        var instance = lambdaProvider.GetService<IRepository>();
    }

    [Benchmark]
    public void ManualDecorator()
    {
        var instance = manualProvider.GetService<IRepository>();
    }
}
```

The results as follows
```
          Method |        Mean |     Error |    StdDev |
---------------- |------------:|----------:|----------:|
        Decorate | 2,276.75 ns | 95.751 ns | 282.32 ns |
 LambdaDecorator |   185.99 ns |  7.498 ns |  22.11 ns |
 ManualDecorator |    73.60 ns |  3.427 ns |  10.11 ns |
```

`Decorate` performs more than 10x worse than lambda decorator. 
What's the reason for that?

**Comment by khellang** [comment]
I don't really know. A quick profiling would probably tell. I'm assuming it's the calls to either `ActivatorUtilities.GetServiceOrCreateInstance` or `ActivatorUtilities.CreateInstance` that are expensive.

The decoration solution was never written to be performant. It's purely for convenience. Because the container itself doesn't support it natively, we're forced to use slower methods of doing it. I guess we could do some caching of compiled delegates if `ActivatorUtilities` has helpers for it, but we need to measure first.

**Comment by myshon** [comment]
@khellang seems you're right. 

![image](https://user-images.githubusercontent.com/2204356/49801682-23374780-fd4b-11e8-8c2b-a3bad043fc79.png)

**Comment by khellang** [comment]
Yeah, that's essentially the difference between what you did (manually creating the lambda) and what the `Decorate` method does.

A type can have an arbitrary amount of ctors and those can have an arbitrary amount of parameters. The method also allows you to explicitly "fill in" an arbitrary amount of parameters. This can be expensive to figure out. The reason we use this is to avoid a StackOverflowException. 

I'm guessing it tries to find a matching ctor every time it's called, which is a bit overkill. I'll take a PR if anyone's interested and cares enough to improve this. It might also be worth considering a PR to the `ActivatorUtilities` class.

**Comment by khellang** [comment]
Related; github.com/aspnet/Extensions/issues/693
