### ISSUE TITLE
Decorating open generics with multiple levels of interface inheritance

### ISSUE THREAD

**Issue by wesleypetrowski-iq** [khellang/Scrutor#75]
Using Scrutor 3.0.2, with a minimal repro over at: https://github.com/wpetrowski/DecorateIssue

Possibly related to #68, as the error is the same, but the setup in my case is a bit different.

-----

I've got some registrations for an `IQueryHandler<T>` interface that I'm trying to decorate.  Most of the implementations directly implement the interface:

```
public class GetIntQueryHandler : IQueryHandler<int> {}
public class GetDoubleQueryHandler : IQueryHandler<double> {}
```

Decorating those kinds of classes works fine:

```
services.Scan(scan => scan
    .FromApplicationDependencies()
        .AddClasses(classes => classes.AssignableTo(typeof(IQueryHandler<>)).Where(type => type != typeof(Decorator<>)))
            .AsImplementedInterfaces());

services.Decorate(typeof(IQueryHandler<>), typeof(Decorator<>));
```

However there are a few query handlers that have some deeper levels of inheritance:
```
public interface IMySpecialHandler : IQueryHandler<string> {}
public class MySpecialHandler : IMySpecialHandler {}
```

When I add in these classes, I get the following error on startup:
```
System.ArgumentException
  Message=The number of generic arguments provided doesn't equal the arity of the generic type definition.
  StackTrace:
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c__DisplayClass13_0.<TryDecorateOpenGeneric>g__TryDecorate|0(Type[] typeArguments)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.DecorateOpenGeneric(IServiceCollection services, Type serviceType, Type decoratorType)
   at DecorationIssue.Startup.ConfigureServices(IServiceCollection services)
```

It seems to be related to the way it's filtering the descriptors: https://github.com/khellang/Scrutor/blob/195006f35cc958ef26af050c5ad7b88ec3f5cfdb/src/Scrutor/ServiceCollectionExtensions.Decoration.cs#L251-L254

Because I'm using `AsImplementedInterfaces`, there's a descriptor for `IMySpecialHandler` implemented by `MySpecialHandler`.  And because `IMySpecialHandler` is assignable to `IQueryHandler<>`, it gets picked up by the code above.  However `IMySpecialHandler` doesn't have any GenericTypeArguments which causes the exception in the local TryDecorate function just above, when it tries to call `MakeGenericType` and passes in 0 arguments.

So... after some fiddling, the following argument collection code works for _my_ case:
```
var arguments = services
    .Where(descriptor => descriptor.ServiceType.IsGenericType && descriptor.ServiceType.GetGenericTypeDefinition() == serviceType.GetGenericTypeDefinition())
    .Select(descriptor => descriptor.ServiceType.GenericTypeArguments)
    .ToArray();
```

I couldn't say whether this is a safe change to make in all cases though, or the proper way to fix it.  I could also fix it by being more careful about which things I register, but... `AsImplementedInterfaces` is so convenient. 😄

**Comment by wesleypetrowski-iq** [comment]
@khellang I've got a PR up over at https://github.com/khellang/Scrutor/pull/76 if you want to take a look.

**Comment by khellang** [comment]
Closed with https://github.com/khellang/Scrutor/pull/76. Thanks @wesleypetrowski-iq! ❤️
