### ISSUE TITLE
Decorator with Open Generics and Dependencies

### ISSUE THREAD

**Issue by michaeltnguyen** [khellang/Scrutor#82]
Hi.  Read through the docs and looked through issues, but still having a syntax problem.  Say I a decorator that relies on an additional dependency:

```
interface IHandler<T> {}

class DecoratedHandler<T> : IHandler<T>
    public DecoratedHandler<T>(IHandler<T>, ISomeOtherService) 
```

`ISomeOtherService` is registered in the `ServiceCollection`, and I register concrete types of `IHandler`.

```
services.AddSingleton<IHandler<int>, MyIntHandler>();
```
I'd like to be able to decorate all `IHandler` instances.  I've tried

```
services.Decorate(typeof(IHandler<>), typeof(DecoratedHandler<>))
```
But this is unable to resolve `ISomeOtherService`.  In the docs, it recommends using the service provider to manually create the decorated instance.  This is fine, but now I've lost the open generic.

```
services.Decorate(typeof(IMessageHandler<>), (inner, provider) => new DecoratedHandler<what goes here?>(inner, provider.GetRequiredService<ISomeOtherService>)
```
Do I need to cast `inner`?  Maybe I'm just unfamiliar with generic syntax in CSharp, but any help would be appreciated.

**Comment by khellang** [comment]
This should indeed be possible using the first method you posted. See the `CanInjectServicesIntoDecoratedType` test. I wonder if the fact that it's open generic changes anything... 🤔

**Comment by michaeltnguyen** [comment]
It works, user error!

We were registering the concrete type of `ISomeOtherService` rather than the interface.
```
services.AddSingleton(MyConcreteInstance)
```
which is why `ISomeOtherService` was not being resolved.  Sorry for the false alarm, and thank you for your quick response.
