### ISSUE TITLE
AsSelfWithInterfaces fails with open-generic interfaces

### ISSUE THREAD

**Issue by TFleury** [khellang/Scrutor#84]
Assume you have one generic interface :
```csharp
public interface IDomainEventHandler { }

public interface IDomainEventHandler<TEvent>
    : IDomainEventHandler where TEvent : DomainEvent
{
    void Handle(TEvent e);
}
```
With some non generic implementations :
```csharp
public class SomeEventHandler:
    IDomainEventHandler<EventA>,
    IDomainEventHandler<EventB>
{
    public void Handle(EventA e) { }

    public void Handle(EventB e) { }
}
```
and some generic ones :
```csharp
public class CatchAllDomainEventsHandler<TEvent> :
    IDomainEventHandler<TEvent> where TEvent : DomainEvent
{
    public void Handle(TEvent e) { }
}
```

and you only want one instance of each implementation
```csharp
services.Scan(scan => scan
    .FromApplicationDependencies()
    .AddClasses(classes => classes.AssignableTo<IDomainEventHandler>())
    .AsSelfWithInterfaces()
    .WithScopedLifetime());
```

Building container fails with ``Open generic service type 'IDomainEventHandler`1[TEvent]` requires registering an open generic implementation type.``.

I think that `AsSelfWithInterfaces()` should handle that case and throw during registration or only register closed type implementations.

**Comment by khellang** [comment]
Hmm... So it's failing on `CatchAllDomainEventsHandler<TEvent>`? I'll have to look into this case and write some failing tests. Generics (mixed open and closed) makes things really complicated.
