### ISSUE TITLE
Singleton resolved from different scopes are not the same 

### ISSUE THREAD

**Issue by wadebee** [khellang/Scrutor#86]
I have some test methods where I am trying to test for captive dependencies by resolving from different scopes and then asserting for sameness. Here is an example:
````
        [TestMethod]
        public void SingletonDependenciesAreSameForAllScopes()
        {
            using (IHost host = Setup.TestHostBuilder().Build())
            {
                var claimsDecorator = host.Services.GetRequiredService<IClaimsDecorator>();
                Assert.IsNotNull(claimsDecorator);

                using (var scope = host.Services.CreateScope())
                {
                    Assert.AreSame(claimsDecorator, scope.ServiceProvider.GetRequiredService<IClaimsDecorator>()); 
                    // ^- Fails with Scrutor registration but not with standard registration
                }
            }
        }
````
Setup.TestHostBuilder() is just a testing convenience method used to spin up a host with a test configuration and test registrations (ConfigureAppConfiguration and ConfigureServices). 

The following Scrutor registration fails the above test:
````
services.Scan(
   scan =>
   {
                scan.FromAssemblies(bootstrap.AssembliesToScan)
                .AddClasses(classes => classes.AssignableTo<IClaimsDecorator>())
                    .As<IClaimsDecorator>().AsSelf().WithSingletonLifetime()
   }
);
````
If I comment out the scrutor registration and use the standard registration below, the assertion works as expected:
````
services.AddSingleton<IClaimsDecorator, InfrastructureClaimsDecorator>();
````
Is this a bug or is something else going on here that I am not aware of?

**Comment by khellang** [comment]
Hmm. That's weird... Can you break in the debugger and find the registration in the service collection? What does the lifetime say?

**Comment by wadebee** [comment]
Can you help me locate the service collection registration lifetime setting? I've often wondered how to find this when working with other peoples registrations. Below is a screenshot of where I typically go to see *if* something is registered but I've never found the lifetime.
![image](https://user-images.githubusercontent.com/81402/55731195-cb060e80-59e7-11e9-8543-e0330f8f49b5.png)

**Comment by wadebee** [comment]
I may have just found lifetime under the CallSiteFactory node shown above. If this is the correct lookup location it looks as if IClaimsDecorator is registered as a transient despite the scrutor .WithSingletonLifetime() registration. 

![image](https://user-images.githubusercontent.com/81402/55732278-bb87c500-59e9-11e9-93eb-c3b3f30fc327.png)

**Comment by wadebee** [comment]
Here is something that may assist you in tracking this down. If I remove the .AsSelf() chained method from my current registration (shown below) Scrutor will then register as a Singleton properly. This is a problem as I lose the ability to resolve the concrete types provided by AsSelf().
````
scan.FromAssemblies(bootstrap.AssembliesToScan)
                .AddClasses(classes => classes.AssignableTo<IClaimsDecorator>())
                    .As<IClaimsDecorator>().AsSelf().WithSingletonLifetime()
````

**Comment by wadebee** [comment]
For anybody else experiencing this problem, here is a workaround until the author can get a fix in place:
````
scan.FromAssemblies(bootstrap.AssembliesToScan)
                .AddClasses(classes => classes.AssignableTo<IClaimsDecorator>())
                    .AsSelf().As<IClaimsDecorator>().WithSingletonLifetime()
````
Chain your AsSelf() in front of your As<IService>() and Scrutor registers properly.

**Comment by khellang** [comment]
Hmm. Thanks for additional details. I'll have to look into the chaining to figure out what's going on. Good thing you found a workaround 😊

**Comment by iPilot** [comment]
Is the different instances for singletones for each interface, that class implements, intented if i use 
`scan.FromApplicationDependencies()
                .AddClasses(c => c.AssignableTo<ISomeInterface>())
                .AsImplementedInterfaces()
                .WithSingletonLifetime()`

**Comment by khellang** [comment]
@iPilot Yes, that's an unfortunate limitation of the container itself. See https://github.com/khellang/Scrutor/issues/57. There's a separate method called `AsSelfWithInterfaces` which will register the type as itself and forward all interface registrations to that conrete registration.

**Comment by khellang** [comment]
This seems to be the same issue as #55, where multiple calls to `As` doesn't properly retain the lifetime information. I have a working fix ready. Closing this to follow up on #55.
