### ISSUE TITLE
Register interfaces with Scrutor when Scrutor is in NuGet 

### ISSUE THREAD

**Issue by CheesePizza100** [khellang/Scrutor#87]
This isn't an issue, I'm just not sure how to resolve this. We have a little message bus in a NuGet package that uses Scrutor to register handlers. Here is the setup from the NuGet library and the interfaces of interest. Will only show commands as I'm sure the solution will be same for events and queries.

```
public static void AddBus(this IServiceCollection services, IConfiguration configuration, Assembly assemblyToScan)
{
      string connectionString = ConstructConnectionString(configuration);

      InitializeBus(services, connectionString, assemblyToScan);
}

public static void InitializeBus(IServiceCollection services, string connectionString, Assembly assemblyToScan)
{
	services.AddSingleton<Dispatcher>();
	services.AddSingleton<ICommandDispatcher>(x => x.GetRequiredService<Dispatcher>());
	services.Decorate<ICommandDispatcher, CommandDispatcherLoggingDecorator>();

	services.AddSingleton<Executor>();
	services.AddSingleton<ICommandExecutor>(x => x.GetRequiredService<Executor>());
	services.Decorate<ICommandExecutor, CommandExecutorLoggingDecorator>();

	services.AddSingleton<ILoggerAdapter<Dispatcher>, LoggerAdapter<Dispatcher>>();
	services.AddSingleton<ILoggerAdapter<Executor>, LoggerAdapter<Executor>>();

	services.Scan(x =>
	{
		Assembly entryAssembly = Assembly.GetEntryAssembly();
		List<Assembly> referencedAssemblies = entryAssembly.GetReferencedAssemblies().Select(y => Assembly.Load(y.Name)).ToList();
		List<Assembly> assemblies = new List<Assembly>() { entryAssembly }.Concat(referencedAssemblies).ToList();
		assemblies.ToList().Add(assemblyToScan);


		x.FromAssemblies(assemblies)
		 .AddClasses(classes => classes.AssignableTo(typeof(ICommandHandler<>)).Where(_ => !_.IsGenericType))
		 .AsImplementedInterfaces()
		 .WithSingletonLifetime();
	});
}

public interface IMessage
{
}

public interface ICommand : IMessage
{
	Guid CorrelationId { get; }
}

public interface IHandler
{
}

public interface ICommandHandler<in T> : IHandler where T : ICommand
{
	Task Execute(T command);
}
```
Here is a sample CommandHandler in an ASP.NET Core Web Api service:
```
public class CreateFooCommandHandler : ICommandHandler<FooCommand>
{
}
```
The Bus package is added to Web Api and in Startup.cs:
```
service.AddBus(Configuration, typeof(CreateFooCommand).Assembly);
```
When trying to hit the CommandHandler, an exception in the bus library is thrown:

> Bus.ExecutorDecorators.CommandExecutorLoggingDecorator[0] No service for type 'MessageBus.ICommandHandler`1[Messages.CreateFooCommand]' 
has been registered. System.InvalidOperationException: No service for type 'Bus.ICommandHandler`1[Messages.FooCommand]'
has been registered at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProvider ServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Bus.Executor.ExecuteCommand[T](T command) at MessageBus.ExecutorDecorators.CommandExecutorLoggingDecorator.ExecuteCommand[T](T command)

If I add this in Statup.cs, everything works fine:
```
services.AddBus(Configuration, typeof(CreateFooCommand).Assembly)
```

Even though Scrutor is in a NuGet package should it be able to pickup registrations such as ICommandHandler<FooCommand> without explicitly wiring it up in Startup.cs?

**Comment by khellang** [comment]
> Even though Scrutor is in a NuGet package should it be able to pickup registrations such as ICommandHandler without explicitly wiring it up in Startup.cs?

Yes, it should, given it's been handed the correct assemblies and the types are matched in the scanning.

BTW, it looks like you're after the `FromApplicationDependencies` method, which does more or less the same as what you're doing :smile:

> `.Where(_ => !_.IsGenericType)`

Why do you have that filter?

> If I add this in Statup.cs, everything works fine:

What does that call do?

**Comment by CheesePizza100** [comment]
FromApplicationDependencies?! :)
Didn't even know about that! Thanks for pointing it out, will change that. Oh I added the IsGenericType check just to see if it made any difference, it doesn't.

I copy and pasted the wrong line. If I add this in Startup.cs everything works fine:
```
services.AddSingleton<ICommandHandler<CreateFooCommand>, CreateFooCommandHandler>();
```
I'll keep tinkering around....

**Comment by CheesePizza100** [comment]
Whoa! That magical FromApplicationDependencies did the trick!

```
services.Scan(x =>
{
      x.FromApplicationDependencies()
      //
}
```
Ty @khellang !

**Comment by khellang** [comment]
![magic](https://user-images.githubusercontent.com/582487/56678373-d6815700-66c2-11e9-8963-087715347154.gif)
