### ISSUE TITLE
typed factory feature

### ISSUE THREAD

**Issue by maciejw** [khellang/Scrutor#97]
Hello, 

I stumbled upon this https://github.com/microsoft/AspNetCoreInjection.TypedFactories but this project is pretty much dead.

I use scrutor and some kind of feature like typed factory would be cool addition.

this is the basic idea of this feature, you can define interface 
```c#
public interface ITestServiceFactory
{
    ITestService Create(string factoryParam1);
}
```
this feature auto generates implementation of this interface on the fly, that creates ITestService 
with dependencies from service provider and also those from Create method itself.

this project uses castle dynamic proxy (castle has this feature built in), but System.Reflection.DispatchProxy.dll works also.

what do you think?

**Comment by khellang** [comment]
Hey @maciejw! 👋

I think it's a neat feature, but I also think it goes way out of scope for what this project wants to tackle. Especially when you start involving dynamic proxies 🤓

What's wrong with the existing project? Just because it looks dead, doesn't mean it is. It might just be "done"? 🤔

**Comment by maciejw** [comment]
@khellang dynamic proxies are not so terrifying c'mon ;) 

My line of reasoning was like this: I use scrutor, it has been published to nuget already, decorator is kind of similar feature its a pattern :) its easy to add, lets ask, 
the other project, no nuget, when publised, this is another package to manage... :)

I'll try with this MS project and let you know :) when nothing happens there I'll drop you PR :)

**Comment by khellang** [comment]
I'm going to close this as we probably won't accept a feature like this in the foreseeable future. I would be cool to see in a side-kick library, though 😉
