### ISSUE TITLE
Any chance we can make TypeSourceSelector public?

### ISSUE THREAD

**Issue by sfmskywalker** [khellang/Scrutor#99]
I have a use case for Scrutor where I'm only interested in assembly scanning without registering the discovered types with `IServiceCollection` (I only need to add them to some collection for different purposes).

Making `TypeSourceSelector` public would allow me to do exactly that.

**Comment by sfmskywalker** [comment]
I just noticed that it would require some more changes. Right now the `ISelector`s can only populate `IServiceCollection`, whereas what I'm after is get my hands on all discovered types. I could of course pass in a dummy `ServiceCollection` and retrieve the results, which I'll go with. But perhaps there's a clean way where we can break apart the coupling between type selection and `IServiceCollection` population. If it's beyond the scope of this project, I would understand. At the same time, the assembly scanning is mighty useful beyond `IServiceCollection` usages IMO.

**Comment by khellang** [comment]
> perhaps there's a clean way where we can break apart the coupling between type selection and `IServiceCollection` population.

Yeah, this is more or less what was requested in https://github.com/khellang/Scrutor/issues/98 as well. As I mentioned in there; I'm not super stoked about pulling this library into two pieces; one for scanning and the other for registration. It's certainly possible, but I'd prefer to keep it a single library as it is today. If you can live with `IServiceCollection` for now, that would be awesome.

**Comment by khellang** [comment]
I guess we could attempt some gymnastics with generics, but I'm afraid it would make everything more complex.

**Comment by sfmskywalker** [comment]
I understand. I can certainly live with `IServiceCollection` - it works and isn't all that bad.
